--liquibase formatted sql

--changeset moneybags:catalog-001
CREATE TABLE DEPOSIT_PRODUCT (
    DEPOSIT_PRODUCT_ID VARCHAR2(36) PRIMARY KEY,
    PRODUCT_CODE VARCHAR2(40) NOT NULL UNIQUE,
    PRODUCT_NAME VARCHAR2(120) NOT NULL,
    DESCRIPTION VARCHAR2(1000),
    DEPOSIT_TYPE VARCHAR2(30) NOT NULL,
    CURRENCY_CODE VARCHAR2(3) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    EFFECTIVE_FROM DATE NOT NULL,
    EFFECTIVE_TO DATE,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY VARCHAR2(100) NOT NULL,
    UPDATED_BY VARCHAR2(100) NOT NULL,
    MIN_OPEN_BAL NUMBER(19,4), MIN_BALANCE NUMBER(19,4), MAX_BALANCE NUMBER(19,4),
    MIN_AMOUNT NUMBER(19,4), MAX_AMOUNT NUMBER(19,4), MIN_TENURE_MONTHS NUMBER(10), MAX_TENURE_MONTHS NUMBER(10),
    OVERDRAFT_ALLOWED NUMBER(1) NOT NULL, OVERDRAFT_LIMIT NUMBER(19,4),
    FD_ALLOWED_TENURE_UNITS VARCHAR2(200), FD_ALLOWED_PAYOUTS VARCHAR2(200), FD_DEFAULT_PAYOUT VARCHAR2(20),
    FD_COMPOUND_FREQ VARCHAR2(20), FD_DAY_COUNT VARCHAR2(20), FD_MIN_HOLD_DAYS NUMBER(10),
    FD_PARTIAL_WITHDRAWAL NUMBER(1) NOT NULL, FD_AUTO_RENEWAL NUMBER(1) NOT NULL,
    FD_MATURITY_INSTRUCTION VARCHAR2(60), FD_MAX_RENEWAL_COUNT NUMBER(10), FD_GRACE_PERIOD_DAYS NUMBER(10),
    CLOSURE_ALLOWED NUMBER(1) NOT NULL, CLOSURE_MODE VARCHAR2(50), MIN_ACCOUNT_AGE_DAYS NUMBER(10), NOTICE_PERIOD_DAYS NUMBER(10),
    CLOSURE_FEE_APPL NUMBER(1) NOT NULL, CLOSURE_FEE_CODE VARCHAR2(60), CLOSURE_FEE_WAIVER_DAYS NUMBER(10),
    ZERO_BALANCE_REQUIRED NUMBER(1) NOT NULL, ACTIVE_RESERVATIONS_OK NUMBER(1) NOT NULL, ACTIVE_MANDATES_OK NUMBER(1) NOT NULL,
    NEGATIVE_BALANCE_OK NUMBER(1) NOT NULL, PENDING_CHARGES_SETTLED NUMBER(1) NOT NULL,
    ALLOWED_CLOSURE_CHANNELS VARCHAR2(500), CLOSURE_SETTLEMENT_METHODS VARCHAR2(500), CLOSURE_APPROVAL_REQUIRED NUMBER(1) NOT NULL,
    CLOSURE_EFFECTIVE_FROM DATE, CLOSURE_EFFECTIVE_TO DATE, CLOSURE_POLICY_VERSION VARCHAR2(40),
    PREMATURE_ALLOWED NUMBER(1) NOT NULL, PREMATURE_MIN_HOLD_DAYS NUMBER(10), PREMATURE_CALC_METHOD VARCHAR2(60),
    PREMATURE_PENALTY_RATE NUMBER(9,4), MIN_PAYABLE_INTEREST_RATE NUMBER(9,4), PRINCIPAL_PENALTY_PCT NUMBER(9,4),
    APPROVAL_ABOVE_AMOUNT NUMBER(19,4), PREMATURE_ALLOWED_CHANNELS VARCHAR2(500), PREMATURE_EFFECTIVE_FROM DATE,
    PREMATURE_EFFECTIVE_TO DATE, PREMATURE_POLICY_VERSION VARCHAR2(40),
    RENEWAL_ALLOWED NUMBER(1) NOT NULL, RENEWAL_OPTIONS VARCHAR2(300), RENEWAL_RATE_APPLICATION VARCHAR2(40),
    RENEWAL_MAX_COUNT NUMBER(10), RENEWAL_POLICY_VERSION VARCHAR2(40),
    CONSTRAINT CK_DEPOSIT_TYPE CHECK (DEPOSIT_TYPE IN ('SAVINGS','CURRENT','FIXED_DEPOSIT')),
    CONSTRAINT CK_DEPOSIT_STATUS CHECK (STATUS IN ('DRAFT','ACTIVE','INACTIVE','DISCONTINUED')),
    CONSTRAINT CK_DEPOSIT_DATES CHECK (EFFECTIVE_TO IS NULL OR EFFECTIVE_TO > EFFECTIVE_FROM)
);
CREATE INDEX IDX_DEPOSIT_PRODUCT_FILTER ON DEPOSIT_PRODUCT (DEPOSIT_TYPE, STATUS, EFFECTIVE_FROM);

CREATE TABLE CREDIT_CARD_PRODUCT (
    CREDIT_CARD_PRODUCT_ID VARCHAR2(36) PRIMARY KEY,
    PRODUCT_CODE VARCHAR2(40) NOT NULL UNIQUE,
    PRODUCT_NAME VARCHAR2(120) NOT NULL,
    DESCRIPTION VARCHAR2(1000), CURRENCY_CODE VARCHAR2(3) NOT NULL, STATUS VARCHAR2(20) NOT NULL,
    EFFECTIVE_FROM DATE NOT NULL, EFFECTIVE_TO DATE,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL, UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY VARCHAR2(100) NOT NULL, UPDATED_BY VARCHAR2(100) NOT NULL,
    CONSTRAINT CK_CC_PRODUCT_STATUS CHECK (STATUS IN ('DRAFT','ACTIVE','INACTIVE','DISCONTINUED')),
    CONSTRAINT CK_CC_PRODUCT_DATES CHECK (EFFECTIVE_TO IS NULL OR EFFECTIVE_TO > EFFECTIVE_FROM)
);
CREATE INDEX IDX_CC_PRODUCT_FILTER ON CREDIT_CARD_PRODUCT (STATUS, EFFECTIVE_FROM);

CREATE TABLE DEPOSIT_INTEREST_POLICY (
    INTEREST_POLICY_ID VARCHAR2(36) PRIMARY KEY, DEPOSIT_PRODUCT_ID VARCHAR2(36) NOT NULL,
    ANNUAL_INTEREST_RATE NUMBER(9,4), PRICING_MODE VARCHAR2(30) NOT NULL, BENCHMARK_CODE VARCHAR2(40),
    PRODUCT_SPREAD NUMBER(9,4), MINIMUM_RATE NUMBER(9,4), MAXIMUM_RATE NUMBER(9,4), TARGET_PROFIT_PERCENTAGE NUMBER(9,4),
    EFFECTIVE_FROM DATE NOT NULL, EFFECTIVE_TO DATE, POLICY_VERSION VARCHAR2(40) NOT NULL,
    CALCULATION_METHOD VARCHAR2(30) NOT NULL, CALCULATION_FREQUENCY VARCHAR2(20) NOT NULL,
    POSTING_FREQUENCY VARCHAR2(20) NOT NULL, COMPOUNDING_FREQUENCY VARCHAR2(20), DAY_COUNT_CONVENTION VARCHAR2(20),
    RATE_APPLICATION_METHOD VARCHAR2(30), INTEREST_TYPE VARCHAR2(10) NOT NULL,
    CONSTRAINT FK_DIP_PRODUCT FOREIGN KEY (DEPOSIT_PRODUCT_ID) REFERENCES DEPOSIT_PRODUCT(DEPOSIT_PRODUCT_ID),
    CONSTRAINT UK_DIP_VERSION UNIQUE (DEPOSIT_PRODUCT_ID, POLICY_VERSION)
);
CREATE INDEX IDX_DIP_EFFECTIVE ON DEPOSIT_INTEREST_POLICY (DEPOSIT_PRODUCT_ID, EFFECTIVE_FROM, EFFECTIVE_TO);

CREATE TABLE CREDIT_CARD_INTEREST_POLICY (
    INTEREST_POLICY_ID VARCHAR2(36) PRIMARY KEY, CREDIT_CARD_PRODUCT_ID VARCHAR2(36) NOT NULL,
    ANNUAL_INTEREST_RATE NUMBER(9,4), PRICING_MODE VARCHAR2(30) NOT NULL, BENCHMARK_CODE VARCHAR2(40),
    PRODUCT_SPREAD NUMBER(9,4), MINIMUM_RATE NUMBER(9,4), MAXIMUM_RATE NUMBER(9,4), TARGET_PROFIT_PERCENTAGE NUMBER(9,4),
    EFFECTIVE_FROM DATE NOT NULL, EFFECTIVE_TO DATE, POLICY_VERSION VARCHAR2(40) NOT NULL,
    CALCULATION_METHOD VARCHAR2(30) NOT NULL, CALCULATION_FREQUENCY VARCHAR2(20) NOT NULL,
    POSTING_FREQUENCY VARCHAR2(20) NOT NULL, COMPOUNDING_FREQUENCY VARCHAR2(20), DAY_COUNT_CONVENTION VARCHAR2(20),
    RATE_APPLICATION_METHOD VARCHAR2(30), INTEREST_TYPE VARCHAR2(10) NOT NULL,
    CONSTRAINT FK_CCIP_PRODUCT FOREIGN KEY (CREDIT_CARD_PRODUCT_ID) REFERENCES CREDIT_CARD_PRODUCT(CREDIT_CARD_PRODUCT_ID),
    CONSTRAINT UK_CCIP_VERSION UNIQUE (CREDIT_CARD_PRODUCT_ID, POLICY_VERSION)
);
CREATE INDEX IDX_CCIP_EFFECTIVE ON CREDIT_CARD_INTEREST_POLICY (CREDIT_CARD_PRODUCT_ID, EFFECTIVE_FROM, EFFECTIVE_TO);

CREATE TABLE CREDIT_CARD_TERMS (
    CREDIT_CARD_TERMS_ID VARCHAR2(36) PRIMARY KEY, CREDIT_CARD_PRODUCT_ID VARCHAR2(36) NOT NULL,
    POLICY_VERSION VARCHAR2(40) NOT NULL, EFFECTIVE_FROM DATE NOT NULL, EFFECTIVE_TO DATE,
    MINIMUM_CREDIT_LIMIT NUMBER(19,4) NOT NULL, MAXIMUM_CREDIT_LIMIT NUMBER(19,4) NOT NULL,
    INTEREST_FREE_DAYS NUMBER(10) NOT NULL, MINIMUM_PAYMENT_PCT NUMBER(9,4) NOT NULL,
    MINIMUM_PAYMENT_AMOUNT NUMBER(19,4) NOT NULL, PAYMENT_DUE_DAYS NUMBER(10) NOT NULL,
    CASH_ADVANCE_ALLOWED NUMBER(1) NOT NULL, CASH_ADVANCE_LIMIT_PCT NUMBER(9,4),
    CONSTRAINT FK_CCT_PRODUCT FOREIGN KEY (CREDIT_CARD_PRODUCT_ID) REFERENCES CREDIT_CARD_PRODUCT(CREDIT_CARD_PRODUCT_ID),
    CONSTRAINT UK_CCT_VERSION UNIQUE (CREDIT_CARD_PRODUCT_ID, POLICY_VERSION)
);
