--liquibase formatted sql

--changeset moneybags:catalog-002
CREATE TABLE DEPOSIT_PRODUCT_FEE (
    DEPOSIT_PRODUCT_ID VARCHAR2(36) NOT NULL, FEE_TYPE VARCHAR2(30) NOT NULL, FEE_AMOUNT NUMBER(19,4),
    FEE_PERCENTAGE NUMBER(9,4), FEE_FREQUENCY VARCHAR2(20) NOT NULL, ACTIVE NUMBER(1) NOT NULL,
    CONSTRAINT FK_DPF_PRODUCT FOREIGN KEY (DEPOSIT_PRODUCT_ID) REFERENCES DEPOSIT_PRODUCT(DEPOSIT_PRODUCT_ID)
);
CREATE TABLE DEPOSIT_PRODUCT_ELIGIBILITY (
    DEPOSIT_PRODUCT_ID VARCHAR2(36) NOT NULL, MINIMUM_AGE NUMBER(10), MAXIMUM_AGE NUMBER(10), MINIMUM_MONTHLY_INCOME NUMBER(19,4),
    CUSTOMER_TYPE VARCHAR2(20) NOT NULL, CUSTOMER_CATEGORY VARCHAR2(30), KYC_REQUIRED NUMBER(1) NOT NULL,
    COLLATERAL_REQUIRED NUMBER(1) NOT NULL, ACTIVE NUMBER(1) NOT NULL,
    CONSTRAINT FK_DPE_PRODUCT FOREIGN KEY (DEPOSIT_PRODUCT_ID) REFERENCES DEPOSIT_PRODUCT(DEPOSIT_PRODUCT_ID)
);
CREATE TABLE DEPOSIT_PRODUCT_FEATURE (
    DEPOSIT_PRODUCT_ID VARCHAR2(36) NOT NULL, FEATURE_NAME VARCHAR2(100) NOT NULL, FEATURE_VALUE VARCHAR2(500), ACTIVE NUMBER(1) NOT NULL,
    CONSTRAINT FK_DPFTR_PRODUCT FOREIGN KEY (DEPOSIT_PRODUCT_ID) REFERENCES DEPOSIT_PRODUCT(DEPOSIT_PRODUCT_ID)
);
CREATE TABLE FIXED_DEPOSIT_RATE_SLAB (
    DEPOSIT_PRODUCT_ID VARCHAR2(36) NOT NULL, SLAB_CODE VARCHAR2(60) NOT NULL, MINIMUM_TENURE NUMBER(10) NOT NULL,
    MAXIMUM_TENURE NUMBER(10) NOT NULL, TENURE_UNIT VARCHAR2(20) NOT NULL, MINIMUM_AMOUNT NUMBER(19,4) NOT NULL,
    MAXIMUM_AMOUNT NUMBER(19,4), CUSTOMER_CATEGORY VARCHAR2(30), ANNUAL_INTEREST_RATE NUMBER(9,4) NOT NULL,
    EFFECTIVE_FROM DATE NOT NULL, EFFECTIVE_TO DATE, ACTIVE NUMBER(1) NOT NULL,
    CONSTRAINT FK_FDRS_PRODUCT FOREIGN KEY (DEPOSIT_PRODUCT_ID) REFERENCES DEPOSIT_PRODUCT(DEPOSIT_PRODUCT_ID),
    CONSTRAINT UK_FDRS_CODE UNIQUE (DEPOSIT_PRODUCT_ID, SLAB_CODE)
);
CREATE TABLE CREDIT_CARD_PRODUCT_FEE (
    CREDIT_CARD_PRODUCT_ID VARCHAR2(36) NOT NULL, FEE_TYPE VARCHAR2(30) NOT NULL, FEE_AMOUNT NUMBER(19,4),
    FEE_PERCENTAGE NUMBER(9,4), FEE_FREQUENCY VARCHAR2(20) NOT NULL, ACTIVE NUMBER(1) NOT NULL,
    CONSTRAINT FK_CCPF_PRODUCT FOREIGN KEY (CREDIT_CARD_PRODUCT_ID) REFERENCES CREDIT_CARD_PRODUCT(CREDIT_CARD_PRODUCT_ID)
);
CREATE TABLE CREDIT_CARD_PRODUCT_ELIGIBILITY (
    CREDIT_CARD_PRODUCT_ID VARCHAR2(36) NOT NULL, MINIMUM_AGE NUMBER(10), MAXIMUM_AGE NUMBER(10), MINIMUM_MONTHLY_INCOME NUMBER(19,4),
    CUSTOMER_TYPE VARCHAR2(20) NOT NULL, CUSTOMER_CATEGORY VARCHAR2(30), KYC_REQUIRED NUMBER(1) NOT NULL,
    COLLATERAL_REQUIRED NUMBER(1) NOT NULL, ACTIVE NUMBER(1) NOT NULL,
    CONSTRAINT FK_CCPE_PRODUCT FOREIGN KEY (CREDIT_CARD_PRODUCT_ID) REFERENCES CREDIT_CARD_PRODUCT(CREDIT_CARD_PRODUCT_ID)
);
CREATE TABLE CREDIT_CARD_PRODUCT_FEATURE (
    CREDIT_CARD_PRODUCT_ID VARCHAR2(36) NOT NULL, FEATURE_NAME VARCHAR2(100) NOT NULL, FEATURE_VALUE VARCHAR2(500), ACTIVE NUMBER(1) NOT NULL,
    CONSTRAINT FK_CCPFT_PRODUCT FOREIGN KEY (CREDIT_CARD_PRODUCT_ID) REFERENCES CREDIT_CARD_PRODUCT(CREDIT_CARD_PRODUCT_ID)
);
