--liquibase formatted sql

--changeset moneybags:catalog-007-add-senior-fixed-deposit-eligibility
INSERT INTO DEPOSIT_PRODUCT_ELIGIBILITY (
    DEPOSIT_PRODUCT_ID, MINIMUM_AGE, MAXIMUM_AGE, MINIMUM_MONTHLY_INCOME,
    CUSTOMER_TYPE, CUSTOMER_CATEGORY, KYC_REQUIRED, COLLATERAL_REQUIRED, ACTIVE
)
SELECT DEPOSIT_PRODUCT_ID, 60, NULL, NULL,
       'INDIVIDUAL', 'SENIOR_CITIZEN', 1, 0, 1
FROM DEPOSIT_PRODUCT product
WHERE product.PRODUCT_CODE = 'FD-REG-001'
  AND NOT EXISTS (
      SELECT 1
      FROM DEPOSIT_PRODUCT_ELIGIBILITY eligibility
      WHERE eligibility.DEPOSIT_PRODUCT_ID = product.DEPOSIT_PRODUCT_ID
        AND eligibility.CUSTOMER_TYPE = 'INDIVIDUAL'
        AND eligibility.CUSTOMER_CATEGORY = 'SENIOR_CITIZEN'
  );
