--liquibase formatted sql

--changeset charuvi:001-create-notification-template
CREATE TABLE notification_template (
    notification_template_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    notification_type VARCHAR2(50) NOT NULL,
    email_subject_template VARCHAR2(500) NOT NULL,
    email_body_template CLOB NOT NULL,
    active NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_notification_template PRIMARY KEY (notification_template_id),
    CONSTRAINT uq_notification_template_type UNIQUE (notification_type),
    CONSTRAINT chk_notification_template_active CHECK (active IN (0, 1))
);

--changeset charuvi:002-create-notification
CREATE TABLE notification (
    notification_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cif_id NUMBER(19) NOT NULL,
    notification_type VARCHAR2(50) NOT NULL,
    source_reference VARCHAR2(200) NOT NULL,
    idempotency_key VARCHAR2(150) NOT NULL,
    request_fingerprint VARCHAR2(64) NOT NULL,
    recipient_email VARCHAR2(320) NOT NULL,
    email_subject VARCHAR2(500) NOT NULL,
    email_body CLOB NOT NULL,
    status VARCHAR2(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    sent_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_notification PRIMARY KEY (notification_id),
    CONSTRAINT uq_notification_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT chk_notification_status CHECK (status IN ('PENDING', 'SENT', 'FAILED'))
);

--changeset charuvi:003-create-delivery-attempt
CREATE TABLE delivery_attempt (
    delivery_attempt_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    notification_id NUMBER(19) NOT NULL,
    attempt_no NUMBER(5) NOT NULL,
    provider VARCHAR2(100) NOT NULL,
    result VARCHAR2(20) NOT NULL,
    provider_reference VARCHAR2(255),
    error_details CLOB,
    attempted_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_delivery_attempt PRIMARY KEY (delivery_attempt_id),
    CONSTRAINT fk_delivery_attempt_notification FOREIGN KEY (notification_id)
        REFERENCES notification (notification_id),
    CONSTRAINT uq_delivery_attempt_number UNIQUE (notification_id, attempt_no),
    CONSTRAINT chk_delivery_attempt_result CHECK (result IN ('SENT', 'FAILED'))
);

--changeset charuvi:004-create-notification-indexes
CREATE INDEX idx_notification_cif_created ON notification (cif_id, created_at DESC);
CREATE INDEX idx_notification_source_reference ON notification (source_reference);
CREATE INDEX idx_notification_status ON notification (status);
