--liquibase formatted sql
--changeset moneybags:credit-card-v5-bill-payment
CREATE TABLE CREDIT_CARD_BILL_PAYMENT
(
    PAYMENT_ID VARCHAR2(64) NOT NULL PRIMARY KEY,
    ACCOUNT_ID NUMBER(19) NOT NULL,
    AMOUNT     NUMBER(19,4) NOT NULL,
    APPLIED_AT TIMESTAMP NOT NULL,
    CONSTRAINT CK_CCBP_AMOUNT_POSITIVE CHECK (AMOUNT > 0)
);
CREATE INDEX IDX_CCBP_ACCOUNT ON CREDIT_CARD_BILL_PAYMENT (ACCOUNT_ID);
