CREATE TABLE EOD_BUSINESS_DATE (
    RECORD_ID NUMBER(1) NOT NULL,
    BUSINESS_DATE DATE NOT NULL,
    STATUS VARCHAR2(24) NOT NULL,
    CUTOFF_AT TIMESTAMP(6) WITH TIME ZONE,
    OPENED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CLOSED_AT TIMESTAMP(6) WITH TIME ZONE,
    VERSION_NO NUMBER(19) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_EOD_BUSINESS_DATE PRIMARY KEY (RECORD_ID),
    CONSTRAINT CK_EOD_BUSINESS_DATE_ID CHECK (RECORD_ID = 1),
    CONSTRAINT CK_EOD_BUSINESS_DATE_STATUS CHECK (STATUS IN ('OPEN','EOD_IN_PROGRESS','EOD_FAILED'))
);
