CREATE TABLE EOD_RUN (
    RUN_ID VARCHAR2(36) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR2(200) NOT NULL,
    BUSINESS_DATE DATE NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    STARTED_BY VARCHAR2(120) NOT NULL,
    STARTED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    COMPLETED_AT TIMESTAMP(6) WITH TIME ZONE,
    VERSION_NO NUMBER(19) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_EOD_RUN PRIMARY KEY (RUN_ID),
    CONSTRAINT UQ_EOD_RUN_IDEMPOTENCY UNIQUE (IDEMPOTENCY_KEY),
    CONSTRAINT CK_EOD_RUN_STATUS CHECK (STATUS IN ('PENDING','RUNNING','FAILED','COMPLETED'))
);
CREATE INDEX IX_EOD_RUN_DATE_STATUS ON EOD_RUN(BUSINESS_DATE, STATUS);
