CREATE TABLE EOD_EXCEPTION (
    EXCEPTION_ID VARCHAR2(36) NOT NULL,
    RUN_ID VARCHAR2(36) NOT NULL,
    STEP_CODE VARCHAR2(60) NOT NULL,
    SEVERITY VARCHAR2(20) NOT NULL,
    ERROR_CODE VARCHAR2(80) NOT NULL,
    DETAILS_JSON CLOB NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    RESOLUTION VARCHAR2(1000),
    RESOLVED_BY VARCHAR2(120),
    RESOLVED_AT TIMESTAMP(6) WITH TIME ZONE,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT PK_EOD_EXCEPTION PRIMARY KEY (EXCEPTION_ID),
    CONSTRAINT FK_EOD_EXCEPTION_RUN FOREIGN KEY (RUN_ID) REFERENCES EOD_RUN(RUN_ID),
    CONSTRAINT CK_EOD_EXCEPTION_SEVERITY CHECK (SEVERITY IN ('WARNING','ERROR','CRITICAL')),
    CONSTRAINT CK_EOD_EXCEPTION_STATUS CHECK (STATUS IN ('OPEN','RESOLVED','WAIVED'))
);
CREATE INDEX IX_EOD_EXCEPTION_RUN_STATUS ON EOD_EXCEPTION(RUN_ID, STATUS);
