CREATE TABLE PAYMENT_EOD_CONTROL (
  CONTROL_ID VARCHAR2(40 CHAR) PRIMARY KEY,
  BUSINESS_DATE DATE,
  CURRENCY_CODE VARCHAR2(3 CHAR),
  INTAKE_OPEN NUMBER(1) DEFAULT 1 NOT NULL,
  CUTOFF_AT TIMESTAMP WITH TIME ZONE,
  REOPENED_AT TIMESTAMP WITH TIME ZONE,
  UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
  VERSION_NO NUMBER(19) DEFAULT 0 NOT NULL,
  CONSTRAINT CK_PAYMENT_EOD_INTAKE_OPEN CHECK (INTAKE_OPEN IN (0, 1)),
  CONSTRAINT CK_PAYMENT_EOD_CURRENCY CHECK (
    CURRENCY_CODE IS NULL OR LENGTH(CURRENCY_CODE) = 3
  )
);
