--liquibase formatted sql

--changeset moneybags:001-create-deposit-account-schema
CREATE TABLE DEPOSIT_ACCOUNT (
    ACCOUNT_ID VARCHAR2(36) NOT NULL,
    ACCOUNT_NUMBER VARCHAR2(34) NOT NULL,
    PRODUCT_ID VARCHAR2(36) NOT NULL,
    PRODUCT_VERSION NUMBER(10) NOT NULL,
    PRODUCT_NAME_SNAPSHOT VARCHAR2(120) NOT NULL,
    CURRENCY_CODE CHAR(3) NOT NULL,
    SERVICING_BRANCH_ID VARCHAR2(36) NOT NULL,
    OPERATING_INSTRUCTION VARCHAR2(30) NOT NULL,
    STATUS VARCHAR2(24) NOT NULL,
    PREVIOUS_SERVICEABLE_STATUS VARCHAR2(24),
    EXTERNAL_REFERENCE VARCHAR2(64),
    OPENED_AT TIMESTAMP(6) WITH TIME ZONE,
    CLOSED_AT TIMESTAMP(6) WITH TIME ZONE,
    VERSION_NO NUMBER(19) DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(100) NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_DEPOSIT_ACCOUNT PRIMARY KEY (ACCOUNT_ID),
    CONSTRAINT UQ_DEPOSIT_ACCOUNT_NO UNIQUE (ACCOUNT_NUMBER),
    CONSTRAINT CK_DEPOSIT_ACCOUNT_STATUS CHECK (STATUS IN
      ('PENDING_ACTIVATION','ACTIVE','BLOCKED','FROZEN','DORMANT','CLOSURE_PENDING','CLOSED'))
);
CREATE INDEX IX_DEPOSIT_PRODUCT_STATUS ON DEPOSIT_ACCOUNT(PRODUCT_ID, STATUS);
CREATE INDEX IX_DEPOSIT_EXTERNAL_REF ON DEPOSIT_ACCOUNT(EXTERNAL_REFERENCE);

CREATE TABLE ACCOUNT_HOLDER (
    HOLDER_ID VARCHAR2(36) NOT NULL,
    ACCOUNT_ID VARCHAR2(36) NOT NULL,
    CUSTOMER_ID VARCHAR2(36) NOT NULL,
    HOLDER_ROLE VARCHAR2(16) NOT NULL,
    AUTHORIZATION_TYPE VARCHAR2(30),
    OWNERSHIP_PCT NUMBER(5,2),
    STATUS VARCHAR2(16) DEFAULT 'ACTIVE' NOT NULL,
    ADDED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    REMOVED_AT TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT PK_ACCOUNT_HOLDER PRIMARY KEY (HOLDER_ID),
    CONSTRAINT FK_HOLDER_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES DEPOSIT_ACCOUNT(ACCOUNT_ID),
    CONSTRAINT UQ_HOLDER_ACCOUNT_CUSTOMER UNIQUE (ACCOUNT_ID, CUSTOMER_ID),
    CONSTRAINT CK_HOLDER_ROLE CHECK (HOLDER_ROLE IN ('PRIMARY','JOINT','AUTHORIZED')),
    CONSTRAINT CK_HOLDER_STATUS CHECK (STATUS IN ('ACTIVE','INACTIVE','REVOKED')),
    CONSTRAINT CK_HOLDER_PCT CHECK (OWNERSHIP_PCT IS NULL OR (OWNERSHIP_PCT >= 0 AND OWNERSHIP_PCT <= 100))
);
CREATE INDEX IX_HOLDER_CUSTOMER ON ACCOUNT_HOLDER(CUSTOMER_ID, STATUS);

CREATE TABLE ACCOUNT_BALANCE (
    ACCOUNT_ID VARCHAR2(36) NOT NULL,
    CURRENCY_CODE CHAR(3) NOT NULL,
    LEDGER_BALANCE NUMBER(19,4) DEFAULT 0 NOT NULL,
    AVAILABLE_BALANCE NUMBER(19,4) DEFAULT 0 NOT NULL,
    BLOCKED_AMOUNT NUMBER(19,4) DEFAULT 0 NOT NULL,
    PROJECTION_VERSION NUMBER(19) DEFAULT 0 NOT NULL,
    AS_OF TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    SOURCE_EVENT_ID VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_ACCOUNT_BALANCE PRIMARY KEY (ACCOUNT_ID),
    CONSTRAINT FK_BALANCE_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES DEPOSIT_ACCOUNT(ACCOUNT_ID),
    CONSTRAINT UQ_BALANCE_EVENT UNIQUE (SOURCE_EVENT_ID),
    CONSTRAINT CK_BALANCE_BLOCKED CHECK (BLOCKED_AMOUNT >= 0)
);

CREATE TABLE ACCOUNT_STATUS_HISTORY (
    HISTORY_ID VARCHAR2(36) NOT NULL,
    ACCOUNT_ID VARCHAR2(36) NOT NULL,
    FROM_STATUS VARCHAR2(24),
    TO_STATUS VARCHAR2(24) NOT NULL,
    REASON_CODE VARCHAR2(40) NOT NULL,
    REASON_TEXT VARCHAR2(500),
    CHANGED_BY VARCHAR2(100) NOT NULL,
    ACTOR_TYPE VARCHAR2(20) NOT NULL,
    CORRELATION_ID VARCHAR2(64) NOT NULL,
    CHANGED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_ACCOUNT_STATUS_HISTORY PRIMARY KEY (HISTORY_ID),
    CONSTRAINT FK_STATUS_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES DEPOSIT_ACCOUNT(ACCOUNT_ID)
);
CREATE INDEX IX_STATUS_ACCOUNT_TIME ON ACCOUNT_STATUS_HISTORY(ACCOUNT_ID, CHANGED_AT);

CREATE TABLE ACCOUNT_LIMIT (
    LIMIT_ID VARCHAR2(36) NOT NULL,
    ACCOUNT_ID VARCHAR2(36) NOT NULL,
    LIMIT_TYPE VARCHAR2(40) NOT NULL,
    AMOUNT NUMBER(19,4) NOT NULL,
    CURRENCY_CODE CHAR(3) NOT NULL,
    EFFECTIVE_FROM TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    EFFECTIVE_TO TIMESTAMP(6) WITH TIME ZONE,
    VERSION_NO NUMBER(19) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_ACCOUNT_LIMIT PRIMARY KEY (LIMIT_ID),
    CONSTRAINT FK_LIMIT_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES DEPOSIT_ACCOUNT(ACCOUNT_ID),
    CONSTRAINT CK_LIMIT_AMOUNT CHECK (AMOUNT >= 0),
    CONSTRAINT CK_LIMIT_DATES CHECK (EFFECTIVE_TO IS NULL OR EFFECTIVE_TO > EFFECTIVE_FROM)
);
CREATE INDEX IX_LIMIT_ACCOUNT_TYPE ON ACCOUNT_LIMIT(ACCOUNT_ID, LIMIT_TYPE, EFFECTIVE_FROM);

CREATE TABLE ACCOUNT_NOMINEE (
    NOMINEE_ID VARCHAR2(36) NOT NULL,
    ACCOUNT_ID VARCHAR2(36) NOT NULL,
    CUSTOMER_REFERENCE VARCHAR2(36),
    NOMINEE_NAME_CIPHER CLOB,
    RELATIONSHIP_CODE VARCHAR2(30) NOT NULL,
    ALLOCATION_PCT NUMBER(5,2) NOT NULL,
    STATUS VARCHAR2(16) DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_ACCOUNT_NOMINEE PRIMARY KEY (NOMINEE_ID),
    CONSTRAINT FK_NOMINEE_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES DEPOSIT_ACCOUNT(ACCOUNT_ID),
    CONSTRAINT CK_NOMINEE_PCT CHECK (ALLOCATION_PCT > 0 AND ALLOCATION_PCT <= 100)
);

CREATE TABLE ACCOUNT_MANDATE (
    MANDATE_ID VARCHAR2(36) NOT NULL,
    ACCOUNT_ID VARCHAR2(36) NOT NULL,
    AUTHORIZED_CUSTOMER_ID VARCHAR2(36) NOT NULL,
    MANDATE_TYPE VARCHAR2(30) NOT NULL,
    STATUS VARCHAR2(16) DEFAULT 'ACTIVE' NOT NULL,
    VALID_FROM TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    VALID_TO TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT PK_ACCOUNT_MANDATE PRIMARY KEY (MANDATE_ID),
    CONSTRAINT FK_MANDATE_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES DEPOSIT_ACCOUNT(ACCOUNT_ID),
    CONSTRAINT CK_MANDATE_DATES CHECK (VALID_TO IS NULL OR VALID_TO > VALID_FROM)
);

CREATE TABLE IDEMPOTENCY_RECORD (
    RECORD_ID VARCHAR2(36) NOT NULL,
    IDEMPOTENCY_SCOPE VARCHAR2(80) NOT NULL,
    KEY_HASH VARCHAR2(64) NOT NULL,
    REQUEST_HASH VARCHAR2(64) NOT NULL,
    PROCESSING_STATUS VARCHAR2(16) NOT NULL,
    RESOURCE_ID VARCHAR2(36),
    HTTP_STATUS NUMBER(3),
    RESPONSE_BODY CLOB,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    EXPIRES_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT PK_IDEMPOTENCY_RECORD PRIMARY KEY (RECORD_ID),
    CONSTRAINT UQ_IDEMPOTENCY_SCOPE_KEY UNIQUE (IDEMPOTENCY_SCOPE, KEY_HASH)
);
CREATE INDEX IX_IDEMPOTENCY_EXPIRY ON IDEMPOTENCY_RECORD(EXPIRES_AT);

CREATE TABLE OUTBOX_EVENT (
    EVENT_ID VARCHAR2(36) NOT NULL,
    AGGREGATE_ID VARCHAR2(36) NOT NULL,
    AGGREGATE_VERSION NUMBER(19) NOT NULL,
    EVENT_TYPE VARCHAR2(100) NOT NULL,
    PAYLOAD CLOB NOT NULL,
    CORRELATION_ID VARCHAR2(64) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    PUBLISHED_AT TIMESTAMP(6) WITH TIME ZONE,
    PUBLISH_ATTEMPTS NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_OUTBOX_EVENT PRIMARY KEY (EVENT_ID),
    CONSTRAINT CK_OUTBOX_JSON CHECK (PAYLOAD IS JSON)
);
CREATE INDEX IX_OUTBOX_UNPUBLISHED ON OUTBOX_EVENT(PUBLISHED_AT, CREATED_AT);

CREATE TABLE AUDIT_LOG (
    AUDIT_ID VARCHAR2(36) NOT NULL,
    AGGREGATE_ID VARCHAR2(36),
    ACTION VARCHAR2(80) NOT NULL,
    OUTCOME VARCHAR2(20) NOT NULL,
    ACTOR_ID VARCHAR2(100) NOT NULL,
    ACTOR_TYPE VARCHAR2(20) NOT NULL,
    REASON_CODE VARCHAR2(40),
    BEFORE_HASH VARCHAR2(64),
    AFTER_HASH VARCHAR2(64),
    CORRELATION_ID VARCHAR2(64) NOT NULL,
    OCCURRED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_AUDIT_LOG PRIMARY KEY (AUDIT_ID)
);
CREATE INDEX IX_AUDIT_AGGREGATE_TIME ON AUDIT_LOG(AGGREGATE_ID, OCCURRED_AT);
