server:
  port: ${SERVER_PORT:8083}
  shutdown: graceful

spring:
  config:
    import: optional:file:.env[.properties],optional:file:../.env[.properties]
  application:
    name: product-master-service
  datasource:
    url: ${MONEYBAGS_DB_URL:${PRODUCT_MASTER_DB_URL:jdbc:oracle:thin:@//localhost:1522/FREEPDB1}}
    username: ${MONEYBAGS_DB_USERNAME:${PRODUCT_MASTER_DB_USERNAME:moneybags_product}}
    password: ${MONEYBAGS_DB_PASSWORD:${PRODUCT_MASTER_DB_PASSWORD:moneybags_product}}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

eureka:
  client:
    enabled: ${EUREKA_ENABLED:true}
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
