CREATE TABLE ACCOUNT_STATEMENT (
    STATEMENT_ID VARCHAR2(36) NOT NULL,
    CIF_ID VARCHAR2(100) NOT NULL,
    ACCOUNT_REFERENCE VARCHAR2(100) NOT NULL,
    ACCOUNT_TYPE VARCHAR2(40) NOT NULL,
    MASKED_ACCOUNT_REFERENCE VARCHAR2(100) NOT NULL,
    PERIOD_START DATE NOT NULL,
    PERIOD_END DATE NOT NULL,
    CURRENCY_CODE CHAR(3) NOT NULL,
    OPENING_BALANCE NUMBER(19,4) NOT NULL,
    CLOSING_BALANCE NUMBER(19,4) NOT NULL,
    GENERATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    DOCUMENT_SHA256 CHAR(64) NOT NULL,
    DOCUMENT_DATA BLOB NOT NULL,
    CONSTRAINT PK_ACCOUNT_STATEMENT PRIMARY KEY (STATEMENT_ID),
    CONSTRAINT UK_STATEMENT_PERIOD UNIQUE (ACCOUNT_REFERENCE, ACCOUNT_TYPE, PERIOD_START, PERIOD_END),
    CONSTRAINT CK_STATEMENT_STATUS CHECK (STATUS IN ('GENERATED'))
);
CREATE TABLE ACCOUNT_STATEMENT_LINE (
    LINE_ID VARCHAR2(36) NOT NULL,
    STATEMENT_ID VARCHAR2(36) NOT NULL,
    LINE_SEQUENCE NUMBER(10) NOT NULL,
    OCCURRED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    DESCRIPTION VARCHAR2(500) NOT NULL,
    DEBIT_AMOUNT NUMBER(19,4) NOT NULL,
    CREDIT_AMOUNT NUMBER(19,4) NOT NULL,
    BALANCE_AFTER NUMBER(19,4) NOT NULL,
    JOURNAL_NUMBER VARCHAR2(60),
    CONSTRAINT PK_ACCOUNT_STATEMENT_LINE PRIMARY KEY (LINE_ID),
    CONSTRAINT FK_STATEMENT_LINE_STATEMENT FOREIGN KEY (STATEMENT_ID) REFERENCES ACCOUNT_STATEMENT (STATEMENT_ID),
    CONSTRAINT UK_STATEMENT_LINE_SEQUENCE UNIQUE (STATEMENT_ID, LINE_SEQUENCE)
);
CREATE INDEX IX_STATEMENT_CIF_GENERATED ON ACCOUNT_STATEMENT (CIF_ID, GENERATED_AT);
CREATE INDEX IX_STATEMENT_LINE_STATEMENT ON ACCOUNT_STATEMENT_LINE (STATEMENT_ID, LINE_SEQUENCE);
