--liquibase formatted sql

--changeset moneybags:003-add-payment-operations
CREATE TABLE FUND_RESERVATION (
    RESERVATION_ID VARCHAR2(36) NOT NULL,
    PAYMENT_ID VARCHAR2(64) NOT NULL,
    OPERATION_TYPE VARCHAR2(32) NOT NULL,
    SOURCE_ACCOUNT_ID VARCHAR2(36) NOT NULL,
    TARGET_ACCOUNT_ID VARCHAR2(36),
    EXTERNAL_TARGET_ID VARCHAR2(64),
    REQUESTOR_CUSTOMER_ID VARCHAR2(36) NOT NULL,
    AMOUNT NUMBER(19,4) NOT NULL,
    CURRENCY_CODE CHAR(3) NOT NULL,
    STATUS VARCHAR2(16) NOT NULL,
    EXPIRES_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    VERSION_NO NUMBER(19) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_FUND_RESERVATION PRIMARY KEY (RESERVATION_ID),
    CONSTRAINT FK_RESERVATION_SOURCE FOREIGN KEY (SOURCE_ACCOUNT_ID) REFERENCES DEPOSIT_ACCOUNT(ACCOUNT_ID),
    CONSTRAINT FK_RESERVATION_TARGET FOREIGN KEY (TARGET_ACCOUNT_ID) REFERENCES DEPOSIT_ACCOUNT(ACCOUNT_ID),
    CONSTRAINT UQ_RESERVATION_PAYMENT_OP UNIQUE (PAYMENT_ID, OPERATION_TYPE),
    CONSTRAINT CK_RESERVATION_AMOUNT CHECK (AMOUNT > 0),
    CONSTRAINT CK_RESERVATION_STATUS CHECK (STATUS IN ('ACTIVE','CAPTURED','SETTLED','RELEASED','EXPIRED')),
    CONSTRAINT CK_RESERVATION_TARGET CHECK (
      (OPERATION_TYPE = 'BOOK_TRANSFER' AND TARGET_ACCOUNT_ID IS NOT NULL AND EXTERNAL_TARGET_ID IS NULL)
      OR (OPERATION_TYPE = 'CREDIT_CARD_REPAYMENT' AND TARGET_ACCOUNT_ID IS NULL AND EXTERNAL_TARGET_ID IS NOT NULL)
    )
);
CREATE INDEX IX_RESERVATION_EXPIRY ON FUND_RESERVATION(STATUS, EXPIRES_AT);
CREATE INDEX IX_RESERVATION_SOURCE ON FUND_RESERVATION(SOURCE_ACCOUNT_ID, STATUS);

CREATE TABLE DEPOSIT_ACCOUNT_TRANSACTION (
    TRANSACTION_ID VARCHAR2(36) NOT NULL,
    ACCOUNT_ID VARCHAR2(36) NOT NULL,
    PAYMENT_ID VARCHAR2(64) NOT NULL,
    RESERVATION_ID VARCHAR2(36) NOT NULL,
    TRANSACTION_TYPE VARCHAR2(20) NOT NULL,
    OPERATION_TYPE VARCHAR2(32) NOT NULL,
    AMOUNT NUMBER(19,4) NOT NULL,
    CURRENCY_CODE CHAR(3) NOT NULL,
    BALANCE_BEFORE NUMBER(19,4) NOT NULL,
    BALANCE_AFTER NUMBER(19,4) NOT NULL,
    CORRELATION_ID VARCHAR2(64) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_DEPOSIT_TRANSACTION PRIMARY KEY (TRANSACTION_ID),
    CONSTRAINT FK_TRANSACTION_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES DEPOSIT_ACCOUNT(ACCOUNT_ID),
    CONSTRAINT FK_TRANSACTION_RESERVATION FOREIGN KEY (RESERVATION_ID) REFERENCES FUND_RESERVATION(RESERVATION_ID),
    CONSTRAINT CK_TRANSACTION_TYPE CHECK (TRANSACTION_TYPE IN ('PAYMENT_HOLD','HOLD_RELEASE','DEBIT','CREDIT')),
    CONSTRAINT CK_TRANSACTION_AMOUNT CHECK (AMOUNT > 0)
);
CREATE INDEX IX_TRANSACTION_PAYMENT ON DEPOSIT_ACCOUNT_TRANSACTION(PAYMENT_ID, CREATED_AT);
CREATE INDEX IX_TRANSACTION_ACCOUNT ON DEPOSIT_ACCOUNT_TRANSACTION(ACCOUNT_ID, CREATED_AT);
CREATE UNIQUE INDEX UQ_TRANSACTION_EFFECT ON DEPOSIT_ACCOUNT_TRANSACTION(
    PAYMENT_ID, ACCOUNT_ID, TRANSACTION_TYPE
);

--rollback DROP TABLE DEPOSIT_ACCOUNT_TRANSACTION CASCADE CONSTRAINTS;
--rollback DROP TABLE FUND_RESERVATION CASCADE CONSTRAINTS;
