-- Idempotent Oracle seed data for local Swagger/Postman testing.
-- The IDs are deliberately stable so the collection works without manual setup.

MERGE INTO DEPOSIT_ACCOUNT d
USING (SELECT 'seed-sav-source-001' ACCOUNT_ID FROM dual) s
ON (d.ACCOUNT_ID = s.ACCOUNT_ID)
WHEN NOT MATCHED THEN INSERT
  (ACCOUNT_ID, ACCOUNT_NUMBER, PRODUCT_ID, PRODUCT_VERSION, PRODUCT_NAME_SNAPSHOT,
   CURRENCY_CODE, SERVICING_BRANCH_ID, OPERATING_INSTRUCTION, STATUS, OPENED_AT,
   VERSION_NO, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, EXTERNAL_REFERENCE)
VALUES
  ('seed-sav-source-001', 'MBSEEDSAV00000001', 'SAV-001', 1, 'Seed Savings Account',
   'INR', 'BR-001', 'SINGLE', 'ACTIVE', SYSTIMESTAMP, 0,
   SYSTIMESTAMP, 'liquibase-seed', SYSTIMESTAMP, 'liquibase-seed', 'POSTMAN-SOURCE');

MERGE INTO DEPOSIT_ACCOUNT d
USING (SELECT 'seed-cur-target-001' ACCOUNT_ID FROM dual) s
ON (d.ACCOUNT_ID = s.ACCOUNT_ID)
WHEN NOT MATCHED THEN INSERT
  (ACCOUNT_ID, ACCOUNT_NUMBER, PRODUCT_ID, PRODUCT_VERSION, PRODUCT_NAME_SNAPSHOT,
   CURRENCY_CODE, SERVICING_BRANCH_ID, OPERATING_INSTRUCTION, STATUS, OPENED_AT,
   VERSION_NO, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, EXTERNAL_REFERENCE)
VALUES
  ('seed-cur-target-001', 'MBSEEDCUR00000001', 'CUR-001', 1, 'Seed Current Account',
   'INR', 'BR-001', 'SINGLE', 'ACTIVE', SYSTIMESTAMP, 0,
   SYSTIMESTAMP, 'liquibase-seed', SYSTIMESTAMP, 'liquibase-seed', 'POSTMAN-TARGET');

MERGE INTO DEPOSIT_ACCOUNT d
USING (SELECT 'seed-sav-pending-001' ACCOUNT_ID FROM dual) s
ON (d.ACCOUNT_ID = s.ACCOUNT_ID)
WHEN NOT MATCHED THEN INSERT
  (ACCOUNT_ID, ACCOUNT_NUMBER, PRODUCT_ID, PRODUCT_VERSION, PRODUCT_NAME_SNAPSHOT,
   CURRENCY_CODE, SERVICING_BRANCH_ID, OPERATING_INSTRUCTION, STATUS,
   VERSION_NO, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, EXTERNAL_REFERENCE)
VALUES
  ('seed-sav-pending-001', 'MBSEEDSAV00000002', 'SAV-001', 1, 'Seed Pending Savings',
   'INR', 'BR-001', 'SINGLE', 'PENDING_ACTIVATION', 0,
   SYSTIMESTAMP, 'liquibase-seed', SYSTIMESTAMP, 'liquibase-seed', 'POSTMAN-PENDING');

MERGE INTO DEPOSIT_ACCOUNT d
USING (SELECT 'seed-sav-blocked-001' ACCOUNT_ID FROM dual) s
ON (d.ACCOUNT_ID = s.ACCOUNT_ID)
WHEN NOT MATCHED THEN INSERT
  (ACCOUNT_ID, ACCOUNT_NUMBER, PRODUCT_ID, PRODUCT_VERSION, PRODUCT_NAME_SNAPSHOT,
   CURRENCY_CODE, SERVICING_BRANCH_ID, OPERATING_INSTRUCTION, STATUS, OPENED_AT,
   VERSION_NO, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, EXTERNAL_REFERENCE)
VALUES
  ('seed-sav-blocked-001', 'MBSEEDSAV00000003', 'SAV-001', 1, 'Seed Blocked Savings',
   'INR', 'BR-002', 'SINGLE', 'BLOCKED', SYSTIMESTAMP, 0,
   SYSTIMESTAMP, 'liquibase-seed', SYSTIMESTAMP, 'liquibase-seed', 'POSTMAN-BLOCKED');

MERGE INTO DEPOSIT_ACCOUNT d
USING (SELECT 'seed-cur-dormant-001' ACCOUNT_ID FROM dual) s
ON (d.ACCOUNT_ID = s.ACCOUNT_ID)
WHEN NOT MATCHED THEN INSERT
  (ACCOUNT_ID, ACCOUNT_NUMBER, PRODUCT_ID, PRODUCT_VERSION, PRODUCT_NAME_SNAPSHOT,
   CURRENCY_CODE, SERVICING_BRANCH_ID, OPERATING_INSTRUCTION, STATUS, OPENED_AT,
   VERSION_NO, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, EXTERNAL_REFERENCE)
VALUES
  ('seed-cur-dormant-001', 'MBSEEDCUR00000002', 'CUR-001', 1, 'Seed Dormant Current',
   'INR', 'BR-002', 'SINGLE', 'DORMANT', SYSTIMESTAMP, 0,
   SYSTIMESTAMP, 'liquibase-seed', SYSTIMESTAMP, 'liquibase-seed', 'POSTMAN-DORMANT');

MERGE INTO ACCOUNT_HOLDER h
USING (SELECT 'seed-holder-source-001' HOLDER_ID FROM dual) s ON (h.HOLDER_ID = s.HOLDER_ID)
WHEN NOT MATCHED THEN INSERT
  (HOLDER_ID, ACCOUNT_ID, CUSTOMER_ID, HOLDER_ROLE, AUTHORIZATION_TYPE, OWNERSHIP_PCT, STATUS, ADDED_AT)
VALUES ('seed-holder-source-001', 'seed-sav-source-001', 'CIF-1001', 'PRIMARY', 'SINGLE', 100, 'ACTIVE', SYSTIMESTAMP);

MERGE INTO ACCOUNT_HOLDER h
USING (SELECT 'seed-holder-target-001' HOLDER_ID FROM dual) s ON (h.HOLDER_ID = s.HOLDER_ID)
WHEN NOT MATCHED THEN INSERT
  (HOLDER_ID, ACCOUNT_ID, CUSTOMER_ID, HOLDER_ROLE, AUTHORIZATION_TYPE, OWNERSHIP_PCT, STATUS, ADDED_AT)
VALUES ('seed-holder-target-001', 'seed-cur-target-001', 'CIF-2001', 'PRIMARY', 'SINGLE', 100, 'ACTIVE', SYSTIMESTAMP);

MERGE INTO ACCOUNT_HOLDER h
USING (SELECT 'seed-holder-pending-001' HOLDER_ID FROM dual) s ON (h.HOLDER_ID = s.HOLDER_ID)
WHEN NOT MATCHED THEN INSERT
  (HOLDER_ID, ACCOUNT_ID, CUSTOMER_ID, HOLDER_ROLE, AUTHORIZATION_TYPE, OWNERSHIP_PCT, STATUS, ADDED_AT)
VALUES ('seed-holder-pending-001', 'seed-sav-pending-001', 'CIF-3001', 'PRIMARY', 'SINGLE', 100, 'ACTIVE', SYSTIMESTAMP);

MERGE INTO ACCOUNT_HOLDER h
USING (SELECT 'seed-holder-blocked-001' HOLDER_ID FROM dual) s ON (h.HOLDER_ID = s.HOLDER_ID)
WHEN NOT MATCHED THEN INSERT
  (HOLDER_ID, ACCOUNT_ID, CUSTOMER_ID, HOLDER_ROLE, AUTHORIZATION_TYPE, OWNERSHIP_PCT, STATUS, ADDED_AT)
VALUES ('seed-holder-blocked-001', 'seed-sav-blocked-001', 'CIF-4001', 'PRIMARY', 'SINGLE', 100, 'ACTIVE', SYSTIMESTAMP);

MERGE INTO ACCOUNT_HOLDER h
USING (SELECT 'seed-holder-dormant-001' HOLDER_ID FROM dual) s ON (h.HOLDER_ID = s.HOLDER_ID)
WHEN NOT MATCHED THEN INSERT
  (HOLDER_ID, ACCOUNT_ID, CUSTOMER_ID, HOLDER_ROLE, AUTHORIZATION_TYPE, OWNERSHIP_PCT, STATUS, ADDED_AT)
VALUES ('seed-holder-dormant-001', 'seed-cur-dormant-001', 'CIF-5001', 'PRIMARY', 'SINGLE', 100, 'ACTIVE', SYSTIMESTAMP);

MERGE INTO ACCOUNT_BALANCE b
USING (SELECT 'seed-sav-source-001' ACCOUNT_ID FROM dual) s ON (b.ACCOUNT_ID = s.ACCOUNT_ID)
WHEN NOT MATCHED THEN INSERT
  (ACCOUNT_ID, CURRENCY_CODE, LEDGER_BALANCE, AVAILABLE_BALANCE, BLOCKED_AMOUNT,
   PROJECTION_VERSION, AS_OF, SOURCE_EVENT_ID)
VALUES ('seed-sav-source-001', 'INR', 25000, 25000, 0, 0, SYSTIMESTAMP, 'seed-balance-source-001');

MERGE INTO ACCOUNT_BALANCE b
USING (SELECT 'seed-cur-target-001' ACCOUNT_ID FROM dual) s ON (b.ACCOUNT_ID = s.ACCOUNT_ID)
WHEN NOT MATCHED THEN INSERT
  (ACCOUNT_ID, CURRENCY_CODE, LEDGER_BALANCE, AVAILABLE_BALANCE, BLOCKED_AMOUNT,
   PROJECTION_VERSION, AS_OF, SOURCE_EVENT_ID)
VALUES ('seed-cur-target-001', 'INR', 10000, 10000, 0, 0, SYSTIMESTAMP, 'seed-balance-target-001');

MERGE INTO ACCOUNT_BALANCE b
USING (SELECT 'seed-sav-pending-001' ACCOUNT_ID FROM dual) s ON (b.ACCOUNT_ID = s.ACCOUNT_ID)
WHEN NOT MATCHED THEN INSERT
  (ACCOUNT_ID, CURRENCY_CODE, LEDGER_BALANCE, AVAILABLE_BALANCE, BLOCKED_AMOUNT,
   PROJECTION_VERSION, AS_OF, SOURCE_EVENT_ID)
VALUES ('seed-sav-pending-001', 'INR', 0, 0, 0, 0, SYSTIMESTAMP, 'seed-balance-pending-001');

MERGE INTO ACCOUNT_BALANCE b
USING (SELECT 'seed-sav-blocked-001' ACCOUNT_ID FROM dual) s ON (b.ACCOUNT_ID = s.ACCOUNT_ID)
WHEN NOT MATCHED THEN INSERT
  (ACCOUNT_ID, CURRENCY_CODE, LEDGER_BALANCE, AVAILABLE_BALANCE, BLOCKED_AMOUNT,
   PROJECTION_VERSION, AS_OF, SOURCE_EVENT_ID)
VALUES ('seed-sav-blocked-001', 'INR', 1000, 1000, 0, 0, SYSTIMESTAMP, 'seed-balance-blocked-001');

MERGE INTO ACCOUNT_BALANCE b
USING (SELECT 'seed-cur-dormant-001' ACCOUNT_ID FROM dual) s ON (b.ACCOUNT_ID = s.ACCOUNT_ID)
WHEN NOT MATCHED THEN INSERT
  (ACCOUNT_ID, CURRENCY_CODE, LEDGER_BALANCE, AVAILABLE_BALANCE, BLOCKED_AMOUNT,
   PROJECTION_VERSION, AS_OF, SOURCE_EVENT_ID)
VALUES ('seed-cur-dormant-001', 'INR', 500, 500, 0, 0, SYSTIMESTAMP, 'seed-balance-dormant-001');

MERGE INTO ACCOUNT_STATUS_HISTORY h
USING (SELECT 'seed-history-source-001' HISTORY_ID FROM dual) s ON (h.HISTORY_ID = s.HISTORY_ID)
WHEN NOT MATCHED THEN INSERT
  (HISTORY_ID, ACCOUNT_ID, FROM_STATUS, TO_STATUS, REASON_CODE, REASON_TEXT,
   CHANGED_BY, ACTOR_TYPE, CORRELATION_ID, CHANGED_AT)
VALUES ('seed-history-source-001', 'seed-sav-source-001', 'PENDING_ACTIVATION', 'ACTIVE',
        'SEED_ACTIVATED', 'Postman source account', 'liquibase-seed', 'SYSTEM', 'seed-source', SYSTIMESTAMP);

MERGE INTO ACCOUNT_STATUS_HISTORY h
USING (SELECT 'seed-history-target-001' HISTORY_ID FROM dual) s ON (h.HISTORY_ID = s.HISTORY_ID)
WHEN NOT MATCHED THEN INSERT
  (HISTORY_ID, ACCOUNT_ID, FROM_STATUS, TO_STATUS, REASON_CODE, REASON_TEXT,
   CHANGED_BY, ACTOR_TYPE, CORRELATION_ID, CHANGED_AT)
VALUES ('seed-history-target-001', 'seed-cur-target-001', 'PENDING_ACTIVATION', 'ACTIVE',
        'SEED_ACTIVATED', 'Postman target account', 'liquibase-seed', 'SYSTEM', 'seed-target', SYSTIMESTAMP);

MERGE INTO ACCOUNT_STATUS_HISTORY h
USING (SELECT 'seed-history-pending-001' HISTORY_ID FROM dual) s ON (h.HISTORY_ID = s.HISTORY_ID)
WHEN NOT MATCHED THEN INSERT
  (HISTORY_ID, ACCOUNT_ID, FROM_STATUS, TO_STATUS, REASON_CODE, REASON_TEXT,
   CHANGED_BY, ACTOR_TYPE, CORRELATION_ID, CHANGED_AT)
VALUES ('seed-history-pending-001', 'seed-sav-pending-001', NULL, 'PENDING_ACTIVATION',
        'SEED_CREATED', 'Postman pending account', 'liquibase-seed', 'SYSTEM', 'seed-pending', SYSTIMESTAMP);

-- rollback DELETE FROM ACCOUNT_STATUS_HISTORY WHERE HISTORY_ID LIKE 'seed-history-%';
-- rollback DELETE FROM ACCOUNT_BALANCE WHERE SOURCE_EVENT_ID LIKE 'seed-balance-%';
-- rollback DELETE FROM ACCOUNT_HOLDER WHERE HOLDER_ID LIKE 'seed-holder-%';
-- rollback DELETE FROM DEPOSIT_ACCOUNT WHERE ACCOUNT_ID LIKE 'seed-%';
