ALTER TABLE DEPOSIT_ACCOUNT ADD PRODUCT_SUBTYPE VARCHAR2(30) DEFAULT 'SAVINGS' NOT NULL;
UPDATE DEPOSIT_ACCOUNT SET PRODUCT_SUBTYPE = 'CURRENT'
 WHERE UPPER(PRODUCT_ID) LIKE 'CUR%' OR UPPER(PRODUCT_ID) LIKE '%CURRENT%';
ALTER TABLE DEPOSIT_ACCOUNT ADD CONSTRAINT CK_DEPOSIT_PRODUCT_SUBTYPE CHECK (PRODUCT_SUBTYPE IN ('SAVINGS','CURRENT','FIXED_DEPOSIT'));
ALTER TABLE FUND_RESERVATION DROP CONSTRAINT CK_RESERVATION_TARGET;
ALTER TABLE FUND_RESERVATION ADD CONSTRAINT CK_RESERVATION_TARGET CHECK (
  (OPERATION_TYPE IN ('BOOK_TRANSFER','FIXED_DEPOSIT_FUNDING','FIXED_DEPOSIT_MATURITY_PAYOUT') AND TARGET_ACCOUNT_ID IS NOT NULL AND EXTERNAL_TARGET_ID IS NULL)
  OR (OPERATION_TYPE = 'CREDIT_CARD_REPAYMENT' AND TARGET_ACCOUNT_ID IS NULL AND EXTERNAL_TARGET_ID IS NOT NULL)
);

CREATE TABLE FIXED_DEPOSIT (
    FD_ID VARCHAR2(36) NOT NULL, ACCOUNT_ID VARCHAR2(36) NOT NULL,
    PRINCIPAL_AMOUNT NUMBER(19,4) NOT NULL, CURRENCY_CODE CHAR(3) NOT NULL,
    BOOKING_DATE DATE NOT NULL, VALUE_DATE DATE NOT NULL, MATURITY_DATE DATE NOT NULL,
    TENURE_VALUE NUMBER(6) NOT NULL, TENURE_UNIT VARCHAR2(10) NOT NULL,
    BOOKED_ANNUAL_RATE NUMBER(12,8) NOT NULL, CALCULATION_METHOD VARCHAR2(30) NOT NULL,
    COMPOUNDING_FREQUENCY VARCHAR2(20) NOT NULL, PAYOUT_FREQUENCY VARCHAR2(20) NOT NULL,
    DAY_COUNT_CONVENTION VARCHAR2(20) NOT NULL, EXPECTED_INTEREST NUMBER(19,4) NOT NULL,
    EXPECTED_MATURITY_AMOUNT NUMBER(19,4) NOT NULL, ACCRUED_INTEREST NUMBER(19,4) DEFAULT 0 NOT NULL,
    PAID_INTEREST NUMBER(19,4) DEFAULT 0 NOT NULL, FUNDING_ACCOUNT_ID VARCHAR2(36) NOT NULL,
    PAYOUT_ACCOUNT_ID VARCHAR2(36) NOT NULL, LAST_ACCRUAL_DATE DATE, STATUS VARCHAR2(30) NOT NULL,
    VERSION_NO NUMBER(19) DEFAULT 0 NOT NULL, CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_FIXED_DEPOSIT PRIMARY KEY (FD_ID), CONSTRAINT UQ_FIXED_DEPOSIT_ACCOUNT UNIQUE (ACCOUNT_ID),
    CONSTRAINT FK_FIXED_DEPOSIT_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES DEPOSIT_ACCOUNT(ACCOUNT_ID),
    CONSTRAINT CK_FD_PRINCIPAL CHECK (PRINCIPAL_AMOUNT > 0), CONSTRAINT CK_FD_DATES CHECK (MATURITY_DATE > VALUE_DATE),
    CONSTRAINT CK_FD_STATUS CHECK (STATUS IN ('PENDING_FUNDING','ACTIVE','FUNDING_FAILED','MATURED','PAYOUT_PENDING','PAID_OUT'))
);
CREATE INDEX IX_FD_STATUS_MATURITY ON FIXED_DEPOSIT(STATUS, MATURITY_DATE);
CREATE INDEX IX_FD_STATUS_ACCRUAL ON FIXED_DEPOSIT(STATUS, LAST_ACCRUAL_DATE);
CREATE INDEX IX_FD_FUNDING_ACCOUNT ON FIXED_DEPOSIT(FUNDING_ACCOUNT_ID);

CREATE TABLE FD_RATE_SNAPSHOT (
    SNAPSHOT_ID VARCHAR2(36) NOT NULL, FD_ID VARCHAR2(36) NOT NULL, PRODUCT_CODE VARCHAR2(40) NOT NULL,
    PRODUCT_VERSION NUMBER(10) NOT NULL, RATE_SLAB_CODE VARCHAR2(80), INTEREST_POLICY_VERSION VARCHAR2(30),
    ANNUAL_RATE NUMBER(12,8) NOT NULL, CALCULATION_METHOD VARCHAR2(30) NOT NULL,
    COMPOUNDING_FREQUENCY VARCHAR2(20) NOT NULL, PAYOUT_FREQUENCY VARCHAR2(20) NOT NULL,
    DAY_COUNT_CONVENTION VARCHAR2(20) NOT NULL, RULE_SNAPSHOT_JSON CLOB NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_FD_RATE_SNAPSHOT PRIMARY KEY (SNAPSHOT_ID), CONSTRAINT UQ_FD_RATE_SNAPSHOT UNIQUE (FD_ID),
    CONSTRAINT FK_FD_RATE_SNAPSHOT FOREIGN KEY (FD_ID) REFERENCES FIXED_DEPOSIT(FD_ID),
    CONSTRAINT CK_FD_RATE_JSON CHECK (RULE_SNAPSHOT_JSON IS JSON)
);

CREATE TABLE FD_INTEREST_ACCRUAL (
    ACCRUAL_ID VARCHAR2(36) NOT NULL, FD_ID VARCHAR2(36) NOT NULL, BUSINESS_DATE DATE NOT NULL,
    ACCRUAL_BASE NUMBER(19,4) NOT NULL, ANNUAL_RATE NUMBER(12,8) NOT NULL, DAY_COUNT_BASIS NUMBER(6) NOT NULL,
    INTEREST_AMOUNT NUMBER(19,4) NOT NULL, CUMULATIVE_INTEREST NUMBER(19,4) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL, SOURCE_REFERENCE VARCHAR2(100) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_FD_INTEREST_ACCRUAL PRIMARY KEY (ACCRUAL_ID),
    CONSTRAINT FK_FD_ACCRUAL FOREIGN KEY (FD_ID) REFERENCES FIXED_DEPOSIT(FD_ID),
    CONSTRAINT UQ_FD_ACCRUAL_DATE UNIQUE (FD_ID, BUSINESS_DATE)
);

CREATE TABLE FD_PAYOUT (
    PAYOUT_ID VARCHAR2(36) NOT NULL, FD_ID VARCHAR2(36) NOT NULL, PAYOUT_TYPE VARCHAR2(20) NOT NULL,
    PRINCIPAL_AMOUNT NUMBER(19,4) NOT NULL, INTEREST_AMOUNT NUMBER(19,4) NOT NULL, NET_AMOUNT NUMBER(19,4) NOT NULL,
    DESTINATION_ACCOUNT_ID VARCHAR2(36) NOT NULL, STATUS VARCHAR2(20) NOT NULL, SOURCE_REFERENCE VARCHAR2(100) NOT NULL,
    FAILURE_CODE VARCHAR2(80), CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    COMPLETED_AT TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT PK_FD_PAYOUT PRIMARY KEY (PAYOUT_ID), CONSTRAINT FK_FD_PAYOUT FOREIGN KEY (FD_ID) REFERENCES FIXED_DEPOSIT(FD_ID),
    CONSTRAINT UQ_FD_PAYOUT_REFERENCE UNIQUE (SOURCE_REFERENCE),
    CONSTRAINT CK_FD_PAYOUT_STATUS CHECK (STATUS IN ('PENDING','COMPLETED','FAILED'))
);
CREATE INDEX IX_FD_PAYOUT_STATUS ON FD_PAYOUT(STATUS, CREATED_AT);
