ALTER TABLE FIXED_DEPOSIT DROP CONSTRAINT CK_FD_STATUS;
ALTER TABLE FIXED_DEPOSIT ADD CONSTRAINT CK_FD_STATUS CHECK (STATUS IN
  ('PENDING_FUNDING','ACTIVE','FUNDING_FAILED','MATURED','PREMATURE_CLOSURE_REQUESTED',
   'PAYOUT_PENDING','PAID_OUT','CLOSED_PREMATURE'));

ALTER TABLE FUND_RESERVATION DROP CONSTRAINT CK_RESERVATION_TARGET;
ALTER TABLE FUND_RESERVATION ADD CONSTRAINT CK_RESERVATION_TARGET CHECK (
  (OPERATION_TYPE IN ('BOOK_TRANSFER','FIXED_DEPOSIT_FUNDING','FIXED_DEPOSIT_MATURITY_PAYOUT',
    'CASA_ACCOUNT_CLOSURE','FIXED_DEPOSIT_PREMATURE_PAYOUT')
    AND TARGET_ACCOUNT_ID IS NOT NULL AND EXTERNAL_TARGET_ID IS NULL)
  OR (OPERATION_TYPE = 'CREDIT_CARD_REPAYMENT' AND TARGET_ACCOUNT_ID IS NULL AND EXTERNAL_TARGET_ID IS NOT NULL)
);

CREATE TABLE ACCOUNT_CLOSURE_REQUEST (
    CLOSURE_REQUEST_ID VARCHAR2(36) NOT NULL,
    ACCOUNT_ID VARCHAR2(36) NOT NULL,
    CLOSURE_TYPE VARCHAR2(32) NOT NULL,
    REQUESTED_BY VARCHAR2(100) NOT NULL,
    REQUESTED_CHANNEL VARCHAR2(30) NOT NULL,
    REQUESTED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    REQUESTED_DATE DATE NOT NULL,
    REASON_CODE VARCHAR2(40) NOT NULL,
    REASON_TEXT VARCHAR2(500),
    DESTINATION_ACCOUNT_ID VARCHAR2(36),
    STATUS VARCHAR2(30) NOT NULL,
    REJECTION_CODE VARCHAR2(80),
    REJECTION_DETAILS VARCHAR2(1000),
    POLICY_VERSION VARCHAR2(30) NOT NULL,
    CORRELATION_ID VARCHAR2(64) NOT NULL,
    VERSION_NO NUMBER(19) DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    COMPLETED_AT TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT PK_ACCOUNT_CLOSURE_REQUEST PRIMARY KEY (CLOSURE_REQUEST_ID),
    CONSTRAINT FK_CLOSURE_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES DEPOSIT_ACCOUNT(ACCOUNT_ID),
    CONSTRAINT FK_CLOSURE_DESTINATION FOREIGN KEY (DESTINATION_ACCOUNT_ID) REFERENCES DEPOSIT_ACCOUNT(ACCOUNT_ID),
    CONSTRAINT CK_CLOSURE_DIFFERENT_ACCOUNT CHECK (DESTINATION_ACCOUNT_ID IS NULL OR DESTINATION_ACCOUNT_ID <> ACCOUNT_ID),
    CONSTRAINT CK_CLOSURE_TYPE CHECK (CLOSURE_TYPE IN ('CASA_CUSTOMER_REQUEST','FD_MATURITY','FD_PREMATURE')),
    CONSTRAINT CK_CLOSURE_STATUS CHECK (STATUS IN ('REQUESTED','VALIDATING','REJECTED','SETTLEMENT_PENDING',
      'READY_TO_CLOSE','PAYOUT_PENDING','CLOSED','SETTLEMENT_FAILED','CANCELLED'))
);
CREATE INDEX IX_CLOSURE_ACCOUNT_TIME ON ACCOUNT_CLOSURE_REQUEST(ACCOUNT_ID, CREATED_AT);
CREATE INDEX IX_CLOSURE_STATUS ON ACCOUNT_CLOSURE_REQUEST(STATUS, UPDATED_AT);

CREATE TABLE ACCOUNT_CLOSURE_CHECK (
    CHECK_ID VARCHAR2(36) NOT NULL,
    CLOSURE_REQUEST_ID VARCHAR2(36) NOT NULL,
    CHECK_CODE VARCHAR2(60) NOT NULL,
    CHECK_STATUS VARCHAR2(10) NOT NULL,
    DETAILS VARCHAR2(1000),
    CHECKED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT PK_ACCOUNT_CLOSURE_CHECK PRIMARY KEY (CHECK_ID),
    CONSTRAINT FK_CLOSURE_CHECK_REQUEST FOREIGN KEY (CLOSURE_REQUEST_ID) REFERENCES ACCOUNT_CLOSURE_REQUEST(CLOSURE_REQUEST_ID),
    CONSTRAINT UQ_CLOSURE_CHECK UNIQUE (CLOSURE_REQUEST_ID, CHECK_CODE),
    CONSTRAINT CK_CLOSURE_CHECK_STATUS CHECK (CHECK_STATUS IN ('PASSED','FAILED'))
);

CREATE TABLE ACCOUNT_CLOSURE_SETTLEMENT (
    SETTLEMENT_ID VARCHAR2(36) NOT NULL,
    CLOSURE_REQUEST_ID VARCHAR2(36) NOT NULL,
    PRINCIPAL_AMOUNT NUMBER(19,4) DEFAULT 0 NOT NULL,
    ORIGINAL_INTEREST_AMOUNT NUMBER(19,4) DEFAULT 0 NOT NULL,
    RECALCULATED_INTEREST_AMOUNT NUMBER(19,4) DEFAULT 0 NOT NULL,
    INTEREST_PENALTY_AMOUNT NUMBER(19,4) DEFAULT 0 NOT NULL,
    CLOSURE_FEE_AMOUNT NUMBER(19,4) DEFAULT 0 NOT NULL,
    TAX_AMOUNT NUMBER(19,4) DEFAULT 0 NOT NULL,
    NET_PAYOUT_AMOUNT NUMBER(19,4) DEFAULT 0 NOT NULL,
    CURRENCY_CODE CHAR(3) NOT NULL,
    DESTINATION_ACCOUNT_ID VARCHAR2(36),
    TRANSACTION_REFERENCE VARCHAR2(100) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    FAILURE_CODE VARCHAR2(80),
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    COMPLETED_AT TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT PK_ACCOUNT_CLOSURE_SETTLEMENT PRIMARY KEY (SETTLEMENT_ID),
    CONSTRAINT FK_CLOSURE_SETTLEMENT_REQUEST FOREIGN KEY (CLOSURE_REQUEST_ID) REFERENCES ACCOUNT_CLOSURE_REQUEST(CLOSURE_REQUEST_ID),
    CONSTRAINT UQ_CLOSURE_SETTLEMENT_REQUEST UNIQUE (CLOSURE_REQUEST_ID),
    CONSTRAINT UQ_CLOSURE_SETTLEMENT_REF UNIQUE (TRANSACTION_REFERENCE),
    CONSTRAINT CK_CLOSURE_SETTLEMENT_STATUS CHECK (STATUS IN ('PENDING','COMPLETED','FAILED'))
);

CREATE TABLE FD_PREMATURE_CLOSURE_CALC (
    CALCULATION_ID VARCHAR2(36) NOT NULL,
    FD_ID VARCHAR2(36) NOT NULL,
    CLOSURE_REQUEST_ID VARCHAR2(36) NOT NULL,
    VALUE_DATE DATE NOT NULL,
    REQUESTED_CLOSURE_DATE DATE NOT NULL,
    COMPLETED_HOLDING_DAYS NUMBER(10) NOT NULL,
    ORIGINAL_MATURITY_DATE DATE NOT NULL,
    BOOKED_ANNUAL_RATE NUMBER(12,8) NOT NULL,
    APPLICABLE_ANNUAL_RATE NUMBER(12,8) NOT NULL,
    PENALTY_RATE NUMBER(12,8) NOT NULL,
    FINAL_ANNUAL_RATE NUMBER(12,8) NOT NULL,
    ACCRUED_INTEREST NUMBER(19,4) NOT NULL,
    RECALCULATED_INTEREST NUMBER(19,4) NOT NULL,
    ALREADY_PAID_INTEREST NUMBER(19,4) NOT NULL,
    INTEREST_RECOVERY_AMOUNT NUMBER(19,4) NOT NULL,
    NET_INTEREST_AMOUNT NUMBER(19,4) NOT NULL,
    PRINCIPAL_AMOUNT NUMBER(19,4) NOT NULL,
    NET_PAYOUT_AMOUNT NUMBER(19,4) NOT NULL,
    RULE_SNAPSHOT_JSON CLOB NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT PK_FD_PREMATURE_CALC PRIMARY KEY (CALCULATION_ID),
    CONSTRAINT FK_FD_PREMATURE_FD FOREIGN KEY (FD_ID) REFERENCES FIXED_DEPOSIT(FD_ID),
    CONSTRAINT FK_FD_PREMATURE_REQUEST FOREIGN KEY (CLOSURE_REQUEST_ID) REFERENCES ACCOUNT_CLOSURE_REQUEST(CLOSURE_REQUEST_ID),
    CONSTRAINT UQ_FD_PREMATURE_REQUEST UNIQUE (CLOSURE_REQUEST_ID),
    CONSTRAINT CK_FD_PREMATURE_JSON CHECK (RULE_SNAPSHOT_JSON IS JSON)
);
