-- Extended, idempotent local data for the complete Postman collection.
-- This changeset is installed only under the Liquibase "postman" context.
-- It deliberately creates fixed deposits with historical dates because those
-- states cannot be produced immediately through the booking API.

-- Give the shared payment/funding source enough headroom for repeated local runs.
UPDATE ACCOUNT_BALANCE
   SET LEDGER_BALANCE = 250000,
       AVAILABLE_BALANCE = 250000,
       BLOCKED_AMOUNT = 0,
       PROJECTION_VERSION = PROJECTION_VERSION + 1,
       AS_OF = SYSTIMESTAMP,
       SOURCE_EVENT_ID = 'seed-balance-source-008'
 WHERE ACCOUNT_ID = 'seed-sav-source-001';

-- Zero-balance active CASA account for deterministic closure testing.
MERGE INTO DEPOSIT_ACCOUNT d
USING (SELECT 'seed-sav-close-001' ACCOUNT_ID FROM dual) s
ON (d.ACCOUNT_ID = s.ACCOUNT_ID)
WHEN NOT MATCHED THEN INSERT
  (ACCOUNT_ID, ACCOUNT_NUMBER, PRODUCT_ID, PRODUCT_VERSION, PRODUCT_NAME_SNAPSHOT,
   PRODUCT_SUBTYPE, CURRENCY_CODE, SERVICING_BRANCH_ID, OPERATING_INSTRUCTION,
   STATUS, OPENED_AT, VERSION_NO, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY,
   EXTERNAL_REFERENCE)
VALUES
  ('seed-sav-close-001', 'MBSEEDSAVCLOSE001', 'SAV-001', 1, 'Seed Closure Savings',
   'SAVINGS', 'INR', 'BR-001', 'SINGLE', 'ACTIVE', SYSTIMESTAMP, 0,
   SYSTIMESTAMP, 'liquibase-seed', SYSTIMESTAMP, 'liquibase-seed', 'POSTMAN-CLOSURE');

MERGE INTO ACCOUNT_HOLDER h
USING (SELECT 'seed-holder-close-001' HOLDER_ID FROM dual) s
ON (h.HOLDER_ID = s.HOLDER_ID)
WHEN NOT MATCHED THEN INSERT
  (HOLDER_ID, ACCOUNT_ID, CUSTOMER_ID, HOLDER_ROLE, AUTHORIZATION_TYPE,
   OWNERSHIP_PCT, STATUS, ADDED_AT)
VALUES
  ('seed-holder-close-001', 'seed-sav-close-001', 'CIF-7001', 'PRIMARY',
   'SINGLE', 100, 'ACTIVE', SYSTIMESTAMP);

MERGE INTO ACCOUNT_BALANCE b
USING (SELECT 'seed-sav-close-001' ACCOUNT_ID FROM dual) s
ON (b.ACCOUNT_ID = s.ACCOUNT_ID)
WHEN NOT MATCHED THEN INSERT
  (ACCOUNT_ID, CURRENCY_CODE, LEDGER_BALANCE, AVAILABLE_BALANCE, BLOCKED_AMOUNT,
   PROJECTION_VERSION, AS_OF, SOURCE_EVENT_ID)
VALUES
  ('seed-sav-close-001', 'INR', 0, 0, 0, 0, SYSTIMESTAMP,
   'seed-balance-close-001');

MERGE INTO ACCOUNT_STATUS_HISTORY h
USING (SELECT 'seed-history-close-001' HISTORY_ID FROM dual) s
ON (h.HISTORY_ID = s.HISTORY_ID)
WHEN NOT MATCHED THEN INSERT
  (HISTORY_ID, ACCOUNT_ID, FROM_STATUS, TO_STATUS, REASON_CODE, REASON_TEXT,
   CHANGED_BY, ACTOR_TYPE, CORRELATION_ID, CHANGED_AT)
VALUES
  ('seed-history-close-001', 'seed-sav-close-001', 'PENDING_ACTIVATION', 'ACTIVE',
   'SEED_ACTIVATED', 'Postman CASA closure account', 'liquibase-seed', 'SYSTEM',
   'seed-close', SYSTIMESTAMP);

-- Active FD held for 30 days: suitable for a successful premature-closure test.
MERGE INTO DEPOSIT_ACCOUNT d
USING (SELECT 'seed-fd-account-premature-001' ACCOUNT_ID FROM dual) s
ON (d.ACCOUNT_ID = s.ACCOUNT_ID)
WHEN NOT MATCHED THEN INSERT
  (ACCOUNT_ID, ACCOUNT_NUMBER, PRODUCT_ID, PRODUCT_VERSION, PRODUCT_NAME_SNAPSHOT,
   PRODUCT_SUBTYPE, CURRENCY_CODE, SERVICING_BRANCH_ID, OPERATING_INSTRUCTION,
   STATUS, OPENED_AT, VERSION_NO, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY,
   EXTERNAL_REFERENCE)
VALUES
  ('seed-fd-account-premature-001', 'MBSEEDFDPREM00001', 'FD-REG-001', 1,
   'Seed Premature Closure FD', 'FIXED_DEPOSIT', 'INR', 'BR-001', 'SINGLE',
   'ACTIVE', CAST(TRUNC(SYSDATE) - 30 AS TIMESTAMP), 0,
   CAST(TRUNC(SYSDATE) - 30 AS TIMESTAMP), 'liquibase-seed', SYSTIMESTAMP,
   'liquibase-seed', 'POSTMAN-FD-PREMATURE');

MERGE INTO ACCOUNT_HOLDER h
USING (SELECT 'seed-holder-fd-premature-001' HOLDER_ID FROM dual) s
ON (h.HOLDER_ID = s.HOLDER_ID)
WHEN NOT MATCHED THEN INSERT
  (HOLDER_ID, ACCOUNT_ID, CUSTOMER_ID, HOLDER_ROLE, AUTHORIZATION_TYPE,
   OWNERSHIP_PCT, STATUS, ADDED_AT)
VALUES
  ('seed-holder-fd-premature-001', 'seed-fd-account-premature-001', 'CIF-1001',
   'PRIMARY', 'SINGLE', 100, 'ACTIVE', CAST(TRUNC(SYSDATE) - 30 AS TIMESTAMP));

MERGE INTO ACCOUNT_BALANCE b
USING (SELECT 'seed-fd-account-premature-001' ACCOUNT_ID FROM dual) s
ON (b.ACCOUNT_ID = s.ACCOUNT_ID)
WHEN NOT MATCHED THEN INSERT
  (ACCOUNT_ID, CURRENCY_CODE, LEDGER_BALANCE, AVAILABLE_BALANCE, BLOCKED_AMOUNT,
   PROJECTION_VERSION, AS_OF, SOURCE_EVENT_ID)
VALUES
  ('seed-fd-account-premature-001', 'INR', 5000, 0, 0, 0, SYSTIMESTAMP,
   'seed-balance-fd-premature-001');

MERGE INTO FIXED_DEPOSIT f
USING (SELECT 'seed-fd-premature-001' FD_ID FROM dual) s
ON (f.FD_ID = s.FD_ID)
WHEN NOT MATCHED THEN INSERT
  (FD_ID, ACCOUNT_ID, PRINCIPAL_AMOUNT, CURRENCY_CODE, BOOKING_DATE, VALUE_DATE,
   MATURITY_DATE, TENURE_VALUE, TENURE_UNIT, BOOKED_ANNUAL_RATE,
   CALCULATION_METHOD, COMPOUNDING_FREQUENCY, PAYOUT_FREQUENCY,
   DAY_COUNT_CONVENTION, EXPECTED_INTEREST, EXPECTED_MATURITY_AMOUNT,
   ACCRUED_INTEREST, PAID_INTEREST, FUNDING_ACCOUNT_ID, PAYOUT_ACCOUNT_ID,
   LAST_ACCRUAL_DATE, STATUS, VERSION_NO, CREATED_AT, UPDATED_AT)
VALUES
  ('seed-fd-premature-001', 'seed-fd-account-premature-001', 5000, 'INR',
   TRUNC(SYSDATE) - 30, TRUNC(SYSDATE) - 30, TRUNC(SYSDATE) + 335,
   365, 'DAY', 6.75000000, 'COMPOUND_INTEREST', 'QUARTERLY', 'AT_MATURITY',
   'ACTUAL_365', 348.4000, 5348.4000, 27.7397, 0,
   'seed-sav-source-001', 'seed-sav-source-001', TRUNC(SYSDATE) - 1,
   'ACTIVE', 0, CAST(TRUNC(SYSDATE) - 30 AS TIMESTAMP), SYSTIMESTAMP);

MERGE INTO FD_RATE_SNAPSHOT r
USING (SELECT 'seed-rate-fd-premature-001' SNAPSHOT_ID FROM dual) s
ON (r.SNAPSHOT_ID = s.SNAPSHOT_ID)
WHEN NOT MATCHED THEN INSERT
  (SNAPSHOT_ID, FD_ID, PRODUCT_CODE, PRODUCT_VERSION, RATE_SLAB_CODE,
   INTEREST_POLICY_VERSION, ANNUAL_RATE, CALCULATION_METHOD,
   COMPOUNDING_FREQUENCY, PAYOUT_FREQUENCY, DAY_COUNT_CONVENTION,
   RULE_SNAPSHOT_JSON, CREATED_AT)
VALUES
  ('seed-rate-fd-premature-001', 'seed-fd-premature-001', 'FD-REG-001', 1,
   'SEED-30-DAY', 'SEED-POLICY-V1', 6.75000000, 'COMPOUND_INTEREST',
   'QUARTERLY', 'AT_MATURITY', 'ACTUAL_365',
   '{"source":"liquibase-testdata","scenario":"premature-closure"}',
   CAST(TRUNC(SYSDATE) - 30 AS TIMESTAMP));

MERGE INTO ACCOUNT_STATUS_HISTORY h
USING (SELECT 'seed-history-fd-premature-001' HISTORY_ID FROM dual) s
ON (h.HISTORY_ID = s.HISTORY_ID)
WHEN NOT MATCHED THEN INSERT
  (HISTORY_ID, ACCOUNT_ID, FROM_STATUS, TO_STATUS, REASON_CODE, REASON_TEXT,
   CHANGED_BY, ACTOR_TYPE, CORRELATION_ID, CHANGED_AT)
VALUES
  ('seed-history-fd-premature-001', 'seed-fd-account-premature-001',
   'PENDING_ACTIVATION', 'ACTIVE', 'FD_FUNDED', 'Seed FD funded 30 days ago',
   'liquibase-seed', 'SYSTEM', 'seed-fd-premature',
   CAST(TRUNC(SYSDATE) - 30 AS TIMESTAMP));

-- Active FD maturing today with accrual complete through yesterday.
MERGE INTO DEPOSIT_ACCOUNT d
USING (SELECT 'seed-fd-account-maturity-001' ACCOUNT_ID FROM dual) s
ON (d.ACCOUNT_ID = s.ACCOUNT_ID)
WHEN NOT MATCHED THEN INSERT
  (ACCOUNT_ID, ACCOUNT_NUMBER, PRODUCT_ID, PRODUCT_VERSION, PRODUCT_NAME_SNAPSHOT,
   PRODUCT_SUBTYPE, CURRENCY_CODE, SERVICING_BRANCH_ID, OPERATING_INSTRUCTION,
   STATUS, OPENED_AT, VERSION_NO, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY,
   EXTERNAL_REFERENCE)
VALUES
  ('seed-fd-account-maturity-001', 'MBSEEDFDMATU00001', 'FD-REG-001', 1,
   'Seed Maturing Fixed Deposit', 'FIXED_DEPOSIT', 'INR', 'BR-001', 'SINGLE',
   'ACTIVE', CAST(TRUNC(SYSDATE) - 365 AS TIMESTAMP), 0,
   CAST(TRUNC(SYSDATE) - 365 AS TIMESTAMP), 'liquibase-seed', SYSTIMESTAMP,
   'liquibase-seed', 'POSTMAN-FD-MATURITY');

MERGE INTO ACCOUNT_HOLDER h
USING (SELECT 'seed-holder-fd-maturity-001' HOLDER_ID FROM dual) s
ON (h.HOLDER_ID = s.HOLDER_ID)
WHEN NOT MATCHED THEN INSERT
  (HOLDER_ID, ACCOUNT_ID, CUSTOMER_ID, HOLDER_ROLE, AUTHORIZATION_TYPE,
   OWNERSHIP_PCT, STATUS, ADDED_AT)
VALUES
  ('seed-holder-fd-maturity-001', 'seed-fd-account-maturity-001', 'CIF-1001',
   'PRIMARY', 'SINGLE', 100, 'ACTIVE', CAST(TRUNC(SYSDATE) - 365 AS TIMESTAMP));

MERGE INTO ACCOUNT_BALANCE b
USING (SELECT 'seed-fd-account-maturity-001' ACCOUNT_ID FROM dual) s
ON (b.ACCOUNT_ID = s.ACCOUNT_ID)
WHEN NOT MATCHED THEN INSERT
  (ACCOUNT_ID, CURRENCY_CODE, LEDGER_BALANCE, AVAILABLE_BALANCE, BLOCKED_AMOUNT,
   PROJECTION_VERSION, AS_OF, SOURCE_EVENT_ID)
VALUES
  ('seed-fd-account-maturity-001', 'INR', 3000, 0, 0, 0, SYSTIMESTAMP,
   'seed-balance-fd-maturity-001');

MERGE INTO FIXED_DEPOSIT f
USING (SELECT 'seed-fd-maturity-001' FD_ID FROM dual) s
ON (f.FD_ID = s.FD_ID)
WHEN NOT MATCHED THEN INSERT
  (FD_ID, ACCOUNT_ID, PRINCIPAL_AMOUNT, CURRENCY_CODE, BOOKING_DATE, VALUE_DATE,
   MATURITY_DATE, TENURE_VALUE, TENURE_UNIT, BOOKED_ANNUAL_RATE,
   CALCULATION_METHOD, COMPOUNDING_FREQUENCY, PAYOUT_FREQUENCY,
   DAY_COUNT_CONVENTION, EXPECTED_INTEREST, EXPECTED_MATURITY_AMOUNT,
   ACCRUED_INTEREST, PAID_INTEREST, FUNDING_ACCOUNT_ID, PAYOUT_ACCOUNT_ID,
   LAST_ACCRUAL_DATE, STATUS, VERSION_NO, CREATED_AT, UPDATED_AT)
VALUES
  ('seed-fd-maturity-001', 'seed-fd-account-maturity-001', 3000, 'INR',
   TRUNC(SYSDATE) - 365, TRUNC(SYSDATE) - 365, TRUNC(SYSDATE),
   365, 'DAY', 6.00000000, 'COMPOUND_INTEREST', 'QUARTERLY', 'AT_MATURITY',
   'ACTUAL_365', 180.0000, 3180.0000, 180.0000, 0,
   'seed-sav-source-001', 'seed-sav-source-001', TRUNC(SYSDATE) - 1,
   'ACTIVE', 0, CAST(TRUNC(SYSDATE) - 365 AS TIMESTAMP), SYSTIMESTAMP);

MERGE INTO FD_RATE_SNAPSHOT r
USING (SELECT 'seed-rate-fd-maturity-001' SNAPSHOT_ID FROM dual) s
ON (r.SNAPSHOT_ID = s.SNAPSHOT_ID)
WHEN NOT MATCHED THEN INSERT
  (SNAPSHOT_ID, FD_ID, PRODUCT_CODE, PRODUCT_VERSION, RATE_SLAB_CODE,
   INTEREST_POLICY_VERSION, ANNUAL_RATE, CALCULATION_METHOD,
   COMPOUNDING_FREQUENCY, PAYOUT_FREQUENCY, DAY_COUNT_CONVENTION,
   RULE_SNAPSHOT_JSON, CREATED_AT)
VALUES
  ('seed-rate-fd-maturity-001', 'seed-fd-maturity-001', 'FD-REG-001', 1,
   'SEED-MATURITY', 'SEED-POLICY-V1', 6.00000000, 'COMPOUND_INTEREST',
   'QUARTERLY', 'AT_MATURITY', 'ACTUAL_365',
   '{"source":"liquibase-testdata","scenario":"maturity"}',
   CAST(TRUNC(SYSDATE) - 365 AS TIMESTAMP));

MERGE INTO FD_INTEREST_ACCRUAL a
USING (SELECT 'seed-accrual-fd-maturity-001' ACCRUAL_ID FROM dual) s
ON (a.ACCRUAL_ID = s.ACCRUAL_ID)
WHEN NOT MATCHED THEN INSERT
  (ACCRUAL_ID, FD_ID, BUSINESS_DATE, ACCRUAL_BASE, ANNUAL_RATE,
   DAY_COUNT_BASIS, INTEREST_AMOUNT, CUMULATIVE_INTEREST, STATUS,
   SOURCE_REFERENCE, CREATED_AT)
VALUES
  ('seed-accrual-fd-maturity-001', 'seed-fd-maturity-001',
   TRUNC(SYSDATE) - 1, 3000, 6.00000000, 365, 180.0000, 180.0000,
   'POSTED', 'seed-fd-maturity-final-accrual', CAST(TRUNC(SYSDATE) - 1 AS TIMESTAMP));

MERGE INTO ACCOUNT_STATUS_HISTORY h
USING (SELECT 'seed-history-fd-maturity-001' HISTORY_ID FROM dual) s
ON (h.HISTORY_ID = s.HISTORY_ID)
WHEN NOT MATCHED THEN INSERT
  (HISTORY_ID, ACCOUNT_ID, FROM_STATUS, TO_STATUS, REASON_CODE, REASON_TEXT,
   CHANGED_BY, ACTOR_TYPE, CORRELATION_ID, CHANGED_AT)
VALUES
  ('seed-history-fd-maturity-001', 'seed-fd-account-maturity-001',
   'PENDING_ACTIVATION', 'ACTIVE', 'FD_FUNDED', 'Seed FD ready for maturity',
   'liquibase-seed', 'SYSTEM', 'seed-fd-maturity',
   CAST(TRUNC(SYSDATE) - 365 AS TIMESTAMP));

-- rollback DELETE FROM ACCOUNT_STATUS_HISTORY WHERE HISTORY_ID IN ('seed-history-close-001','seed-history-fd-premature-001','seed-history-fd-maturity-001');
-- rollback DELETE FROM FD_INTEREST_ACCRUAL WHERE ACCRUAL_ID = 'seed-accrual-fd-maturity-001';
-- rollback DELETE FROM FD_RATE_SNAPSHOT WHERE SNAPSHOT_ID IN ('seed-rate-fd-premature-001','seed-rate-fd-maturity-001');
-- rollback DELETE FROM FIXED_DEPOSIT WHERE FD_ID IN ('seed-fd-premature-001','seed-fd-maturity-001');
-- rollback DELETE FROM ACCOUNT_BALANCE WHERE ACCOUNT_ID IN ('seed-sav-close-001','seed-fd-account-premature-001','seed-fd-account-maturity-001');
-- rollback DELETE FROM ACCOUNT_HOLDER WHERE HOLDER_ID IN ('seed-holder-close-001','seed-holder-fd-premature-001','seed-holder-fd-maturity-001');
-- rollback DELETE FROM DEPOSIT_ACCOUNT WHERE ACCOUNT_ID IN ('seed-sav-close-001','seed-fd-account-premature-001','seed-fd-account-maturity-001');
