CREATE TABLE NOTIFICATION_OUTBOX (
    OUTBOX_ID VARCHAR2(36) NOT NULL,
    CIF_ID VARCHAR2(36) NOT NULL,
    NOTIFICATION_TYPE VARCHAR2(40) NOT NULL,
    SOURCE_REFERENCE VARCHAR2(100) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR2(160) NOT NULL,
    TEMPLATE_VARIABLES_JSON CLOB NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    ATTEMPT_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    LAST_ERROR VARCHAR2(1000),
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    SENT_AT TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT PK_NOTIFICATION_OUTBOX PRIMARY KEY (OUTBOX_ID),
    CONSTRAINT UQ_NOTIFICATION_OUTBOX_KEY UNIQUE (IDEMPOTENCY_KEY),
    CONSTRAINT CK_NOTIFICATION_OUTBOX_STATUS CHECK (STATUS IN ('PENDING','DELIVERED'))
);
CREATE INDEX IX_NOTIFICATION_OUTBOX_PENDING ON NOTIFICATION_OUTBOX(STATUS, CREATED_AT);
