ALTER TABLE FD_INTEREST_ACCRUAL ADD ACCOUNTING_JOURNAL_NUMBER VARCHAR2(100);
ALTER TABLE FD_INTEREST_ACCRUAL ADD ACCOUNTING_POSTING_STATUS VARCHAR2(20);

ALTER TABLE FD_PAYOUT ADD ACCOUNTING_JOURNAL_NUMBER VARCHAR2(100);
ALTER TABLE FD_PAYOUT ADD ACCOUNTING_POSTING_STATUS VARCHAR2(20);
