-- Billing owns this table. The service-specific name avoids collisions with
-- idempotency tables owned by other services in a shared Oracle schema.
CREATE TABLE BILL_IDEMPOTENCY_RECORD (
    RECORD_ID VARCHAR2(36) NOT NULL,
    IDEMPOTENCY_SCOPE VARCHAR2(100) NOT NULL,
    KEY_HASH VARCHAR2(64) NOT NULL,
    REQUEST_HASH VARCHAR2(64) NOT NULL,
    PROCESSING_STATUS VARCHAR2(16) DEFAULT 'COMPLETED' NOT NULL,
    RESOURCE_ID VARCHAR2(36),
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    EXPIRES_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT PK_BILL_IDEMPOTENCY_RECORD PRIMARY KEY (RECORD_ID),
    CONSTRAINT UQ_BILL_IDEMPOTENCY_KEY UNIQUE (IDEMPOTENCY_SCOPE, KEY_HASH)
);
