CREATE SEQUENCE ACCOUNTING_JOURNAL_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE GL_ACCOUNT (
    GL_ACCOUNT_ID VARCHAR2(36) NOT NULL,
    GL_CODE VARCHAR2(40) NOT NULL,
    NAME VARCHAR2(160) NOT NULL,
    ACCOUNT_TYPE VARCHAR2(20) NOT NULL,
    NORMAL_BALANCE VARCHAR2(10) NOT NULL,
    CURRENCY_CODE CHAR(3) NOT NULL,
    PARENT_GL_CODE VARCHAR2(40),
    STATUS VARCHAR2(20) NOT NULL,
    VERSION_NO NUMBER(19) DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT PK_GL_ACCOUNT PRIMARY KEY (GL_ACCOUNT_ID),
    CONSTRAINT UQ_GL_ACCOUNT_CODE UNIQUE (GL_CODE),
    CONSTRAINT CK_GL_ACCOUNT_TYPE CHECK (ACCOUNT_TYPE IN ('ASSET','LIABILITY','EQUITY','INCOME','EXPENSE')),
    CONSTRAINT CK_GL_NORMAL_BALANCE CHECK (NORMAL_BALANCE IN ('DEBIT','CREDIT')),
    CONSTRAINT CK_GL_STATUS CHECK (STATUS IN ('ACTIVE','INACTIVE'))
);

CREATE TABLE ACCOUNTING_RULE (
    RULE_ID VARCHAR2(36) NOT NULL,
    RULE_CODE VARCHAR2(60) NOT NULL,
    EVENT_TYPE VARCHAR2(60) NOT NULL,
    COMPONENT_TYPE VARCHAR2(40) NOT NULL,
    PRODUCT_CODE VARCHAR2(40),
    CURRENCY_CODE CHAR(3) NOT NULL,
    RULE_VERSION NUMBER(10) NOT NULL,
    DEBIT_MAPPING_CODE VARCHAR2(60) NOT NULL,
    CREDIT_MAPPING_CODE VARCHAR2(60) NOT NULL,
    EFFECTIVE_FROM DATE NOT NULL,
    EFFECTIVE_TO DATE,
    STATUS VARCHAR2(20) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT PK_ACCOUNTING_RULE PRIMARY KEY (RULE_ID),
    CONSTRAINT UQ_ACCOUNTING_RULE_VERSION UNIQUE (RULE_CODE, RULE_VERSION),
    CONSTRAINT CK_ACCOUNTING_RULE_STATUS CHECK (STATUS IN ('ACTIVE','INACTIVE')),
    CONSTRAINT CK_ACCOUNTING_RULE_DATES CHECK (EFFECTIVE_TO IS NULL OR EFFECTIVE_TO >= EFFECTIVE_FROM)
);
CREATE INDEX IX_RULE_RESOLUTION ON ACCOUNTING_RULE(EVENT_TYPE, COMPONENT_TYPE, CURRENCY_CODE, STATUS);

CREATE TABLE SUBLEDGER_MAPPING (
    MAPPING_ID VARCHAR2(36) NOT NULL,
    MAPPING_CODE VARCHAR2(60) NOT NULL,
    PRODUCT_CODE VARCHAR2(40),
    CURRENCY_CODE CHAR(3) NOT NULL,
    GL_CODE VARCHAR2(40) NOT NULL,
    EFFECTIVE_FROM DATE NOT NULL,
    EFFECTIVE_TO DATE,
    STATUS VARCHAR2(20) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT PK_SUBLEDGER_MAPPING PRIMARY KEY (MAPPING_ID),
    CONSTRAINT FK_MAPPING_GL FOREIGN KEY (GL_CODE) REFERENCES GL_ACCOUNT(GL_CODE),
    CONSTRAINT UQ_SUBLEDGER_MAPPING UNIQUE (MAPPING_CODE, PRODUCT_CODE, CURRENCY_CODE, EFFECTIVE_FROM),
    CONSTRAINT CK_MAPPING_STATUS CHECK (STATUS IN ('ACTIVE','INACTIVE')),
    CONSTRAINT CK_MAPPING_DATES CHECK (EFFECTIVE_TO IS NULL OR EFFECTIVE_TO >= EFFECTIVE_FROM)
);
CREATE INDEX IX_MAPPING_RESOLUTION ON SUBLEDGER_MAPPING(MAPPING_CODE, CURRENCY_CODE, STATUS);

CREATE TABLE SUBLEDGER_ACCOUNT (
    SUBLEDGER_ACCOUNT_ID VARCHAR2(36) NOT NULL,
    ACCOUNT_TYPE VARCHAR2(30) NOT NULL,
    ACCOUNT_REFERENCE VARCHAR2(100) NOT NULL,
    PRODUCT_CODE VARCHAR2(40),
    CURRENCY_CODE CHAR(3) NOT NULL,
    LIFECYCLE_STATE VARCHAR2(20) NOT NULL,
    SOURCE_SERVICE VARCHAR2(80) NOT NULL,
    OPENED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CLOSED_AT TIMESTAMP(6) WITH TIME ZONE,
    VERSION_NO NUMBER(19) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_SUBLEDGER_ACCOUNT PRIMARY KEY (SUBLEDGER_ACCOUNT_ID),
    CONSTRAINT UQ_SUBLEDGER_ACCOUNT UNIQUE (ACCOUNT_TYPE, ACCOUNT_REFERENCE),
    CONSTRAINT CK_SUBLEDGER_ACCOUNT_TYPE CHECK (ACCOUNT_TYPE IN ('DEPOSIT_ACCOUNT','CREDIT_CARD_ACCOUNT')),
    CONSTRAINT CK_SUBLEDGER_STATE CHECK (LIFECYCLE_STATE IN ('OPEN','CLOSED'))
);
CREATE INDEX IX_SUBLEDGER_REFERENCE ON SUBLEDGER_ACCOUNT(ACCOUNT_REFERENCE, LIFECYCLE_STATE);

CREATE TABLE ACCOUNT_LIFECYCLE_EVENT (
    LIFECYCLE_EVENT_ID VARCHAR2(36) NOT NULL,
    EVENT_REFERENCE VARCHAR2(160) NOT NULL,
    IDEMPOTENCY_KEY_HASH VARCHAR2(64) NOT NULL,
    REQUEST_HASH VARCHAR2(64) NOT NULL,
    EVENT_TYPE VARCHAR2(40) NOT NULL,
    ACCOUNT_TYPE VARCHAR2(30) NOT NULL,
    ACCOUNT_REFERENCE VARCHAR2(100) NOT NULL,
    BUSINESS_DATE DATE NOT NULL,
    OCCURRED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    REASON_CODE VARCHAR2(40),
    SOURCE_SERVICE VARCHAR2(80) NOT NULL,
    CORRELATION_ID VARCHAR2(64) NOT NULL,
    PROCESSED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT PK_ACCOUNT_LIFECYCLE_EVENT PRIMARY KEY (LIFECYCLE_EVENT_ID),
    CONSTRAINT UQ_LIFECYCLE_EVENT_REFERENCE UNIQUE (EVENT_REFERENCE),
    CONSTRAINT UQ_LIFECYCLE_IDEMPOTENCY UNIQUE (IDEMPOTENCY_KEY_HASH),
    CONSTRAINT CK_LIFECYCLE_ACCOUNT_TYPE CHECK (ACCOUNT_TYPE IN ('DEPOSIT_ACCOUNT','CREDIT_CARD_ACCOUNT'))
);
CREATE INDEX IX_LIFECYCLE_ACCOUNT ON ACCOUNT_LIFECYCLE_EVENT(ACCOUNT_TYPE, ACCOUNT_REFERENCE, PROCESSED_AT);

CREATE TABLE POSTING_REQUEST (
    POSTING_REQUEST_ID VARCHAR2(36) NOT NULL,
    EXTERNAL_REFERENCE VARCHAR2(160) NOT NULL,
    IDEMPOTENCY_KEY_HASH VARCHAR2(64) NOT NULL,
    REQUEST_HASH VARCHAR2(64) NOT NULL,
    SOURCE_SERVICE VARCHAR2(80) NOT NULL,
    EVENT_TYPE VARCHAR2(60) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    JOURNAL_NUMBER VARCHAR2(60),
    RECEIVED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    COMPLETED_AT TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT PK_POSTING_REQUEST PRIMARY KEY (POSTING_REQUEST_ID),
    CONSTRAINT UQ_POSTING_EXTERNAL_REFERENCE UNIQUE (EXTERNAL_REFERENCE),
    CONSTRAINT UQ_POSTING_IDEMPOTENCY_KEY UNIQUE (IDEMPOTENCY_KEY_HASH),
    CONSTRAINT CK_POSTING_STATUS CHECK (STATUS IN ('RECEIVED','POSTED','REJECTED'))
);

CREATE TABLE JOURNAL (
    JOURNAL_ID VARCHAR2(36) NOT NULL,
    JOURNAL_NUMBER VARCHAR2(60) NOT NULL,
    POSTING_SEQUENCE NUMBER(19) NOT NULL,
    EXTERNAL_REFERENCE VARCHAR2(160) NOT NULL,
    SOURCE_SERVICE VARCHAR2(80) NOT NULL,
    EVENT_TYPE VARCHAR2(60) NOT NULL,
    OCCURRED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    BUSINESS_DATE DATE NOT NULL,
    CURRENCY_CODE CHAR(3) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    TOTAL_DEBIT NUMBER(19,4) NOT NULL,
    TOTAL_CREDIT NUMBER(19,4) NOT NULL,
    REVERSES_JOURNAL_NUMBER VARCHAR2(60),
    CORRELATION_ID VARCHAR2(64) NOT NULL,
    POSTED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT PK_JOURNAL PRIMARY KEY (JOURNAL_ID),
    CONSTRAINT UQ_JOURNAL_NUMBER UNIQUE (JOURNAL_NUMBER),
    CONSTRAINT UQ_JOURNAL_SEQUENCE UNIQUE (POSTING_SEQUENCE),
    CONSTRAINT UQ_JOURNAL_EXTERNAL_REFERENCE UNIQUE (EXTERNAL_REFERENCE),
    CONSTRAINT FK_JOURNAL_REVERSAL FOREIGN KEY (REVERSES_JOURNAL_NUMBER) REFERENCES JOURNAL(JOURNAL_NUMBER),
    CONSTRAINT CK_JOURNAL_STATUS CHECK (STATUS IN ('POSTED')),
    CONSTRAINT CK_JOURNAL_BALANCED CHECK (TOTAL_DEBIT = TOTAL_CREDIT),
    CONSTRAINT CK_JOURNAL_TOTAL_POSITIVE CHECK (TOTAL_DEBIT > 0)
);
CREATE INDEX IX_JOURNAL_SEARCH ON JOURNAL(BUSINESS_DATE, SOURCE_SERVICE, EVENT_TYPE);

CREATE TABLE JOURNAL_LINE (
    LINE_ID VARCHAR2(36) NOT NULL,
    JOURNAL_ID VARCHAR2(36) NOT NULL,
    LINE_NUMBER NUMBER(10) NOT NULL,
    GL_CODE VARCHAR2(40) NOT NULL,
    SUBLEDGER_REFERENCE VARCHAR2(100),
    COMPONENT_TYPE VARCHAR2(40) NOT NULL,
    RULE_CODE VARCHAR2(60) NOT NULL,
    RULE_VERSION NUMBER(10) NOT NULL,
    DEBIT_AMOUNT NUMBER(19,4) DEFAULT 0 NOT NULL,
    CREDIT_AMOUNT NUMBER(19,4) DEFAULT 0 NOT NULL,
    NARRATION VARCHAR2(500),
    CONSTRAINT PK_JOURNAL_LINE PRIMARY KEY (LINE_ID),
    CONSTRAINT FK_JOURNAL_LINE_HEADER FOREIGN KEY (JOURNAL_ID) REFERENCES JOURNAL(JOURNAL_ID),
    CONSTRAINT FK_JOURNAL_LINE_GL FOREIGN KEY (GL_CODE) REFERENCES GL_ACCOUNT(GL_CODE),
    CONSTRAINT UQ_JOURNAL_LINE UNIQUE (JOURNAL_ID, LINE_NUMBER),
    CONSTRAINT CK_JOURNAL_LINE_SIDE CHECK ((DEBIT_AMOUNT > 0 AND CREDIT_AMOUNT = 0) OR (CREDIT_AMOUNT > 0 AND DEBIT_AMOUNT = 0))
);
CREATE INDEX IX_JOURNAL_LINE_SUBLEDGER ON JOURNAL_LINE(SUBLEDGER_REFERENCE);
CREATE INDEX IX_JOURNAL_LINE_GL ON JOURNAL_LINE(GL_CODE);

CREATE TABLE ACCOUNTING_PERIOD (
    PERIOD_ID VARCHAR2(36) NOT NULL,
    BUSINESS_DATE DATE NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    OPENED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CLOSED_AT TIMESTAMP(6) WITH TIME ZONE,
    OPENED_BY VARCHAR2(100) NOT NULL,
    CLOSED_BY VARCHAR2(100),
    VERSION_NO NUMBER(19) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_ACCOUNTING_PERIOD PRIMARY KEY (PERIOD_ID),
    CONSTRAINT UQ_ACCOUNTING_PERIOD_DATE UNIQUE (BUSINESS_DATE),
    CONSTRAINT CK_ACCOUNTING_PERIOD_STATUS CHECK (STATUS IN ('OPEN','CLOSING','CLOSED'))
);

CREATE TABLE IDEMPOTENCY_RECORD (
    RECORD_ID VARCHAR2(36) NOT NULL,
    SCOPE VARCHAR2(100) NOT NULL,
    KEY_HASH VARCHAR2(64) NOT NULL,
    REQUEST_HASH VARCHAR2(64) NOT NULL,
    RESOURCE_ID VARCHAR2(100),
    HTTP_STATUS NUMBER(3) NOT NULL,
    RESPONSE_BODY CLOB NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT PK_IDEMPOTENCY_RECORD PRIMARY KEY (RECORD_ID),
    CONSTRAINT UQ_IDEMPOTENCY_SCOPE_KEY UNIQUE (SCOPE, KEY_HASH)
);

CREATE TABLE AUDIT_LOG (
    AUDIT_ID VARCHAR2(36) NOT NULL,
    AGGREGATE_ID VARCHAR2(100) NOT NULL,
    ACTION VARCHAR2(80) NOT NULL,
    OUTCOME VARCHAR2(20) NOT NULL,
    ACTOR_ID VARCHAR2(100),
    ACTOR_TYPE VARCHAR2(30),
    CORRELATION_ID VARCHAR2(64) NOT NULL,
    OCCURRED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT PK_ACCOUNTING_AUDIT_LOG PRIMARY KEY (AUDIT_ID)
);
CREATE INDEX IX_ACCOUNTING_AUDIT_AGG ON AUDIT_LOG(AGGREGATE_ID, OCCURRED_AT);

CREATE TABLE TRIAL_BALANCE_RUN (
    RUN_ID VARCHAR2(36) NOT NULL,
    BUSINESS_DATE DATE NOT NULL,
    CURRENCY_CODE CHAR(3) NOT NULL,
    TOTAL_DEBIT NUMBER(19,4) NOT NULL,
    TOTAL_CREDIT NUMBER(19,4) NOT NULL,
    BALANCED_FLAG NUMBER(1) NOT NULL,
    GENERATED_BY VARCHAR2(100) NOT NULL,
    GENERATED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT PK_TRIAL_BALANCE_RUN PRIMARY KEY (RUN_ID),
    CONSTRAINT UQ_TRIAL_BALANCE_DATE UNIQUE (BUSINESS_DATE, CURRENCY_CODE),
    CONSTRAINT CK_TRIAL_BALANCE_FLAG CHECK (BALANCED_FLAG IN (0,1))
);

CREATE TABLE TRIAL_BALANCE_LINE (
    LINE_ID VARCHAR2(36) NOT NULL,
    RUN_ID VARCHAR2(36) NOT NULL,
    GL_CODE VARCHAR2(40) NOT NULL,
    DEBIT_TOTAL NUMBER(19,4) NOT NULL,
    CREDIT_TOTAL NUMBER(19,4) NOT NULL,
    CLOSING_BALANCE NUMBER(19,4) NOT NULL,
    CONSTRAINT PK_TRIAL_BALANCE_LINE PRIMARY KEY (LINE_ID),
    CONSTRAINT FK_TRIAL_BALANCE_RUN FOREIGN KEY (RUN_ID) REFERENCES TRIAL_BALANCE_RUN(RUN_ID),
    CONSTRAINT FK_TRIAL_BALANCE_GL FOREIGN KEY (GL_CODE) REFERENCES GL_ACCOUNT(GL_CODE),
    CONSTRAINT UQ_TRIAL_BALANCE_LINE UNIQUE (RUN_ID, GL_CODE)
);

CREATE TABLE FIN_RECON_RUN (
    RUN_ID VARCHAR2(36) NOT NULL,
    EOD_RUN_ID VARCHAR2(80) NOT NULL,
    BUSINESS_DATE DATE NOT NULL,
    CURRENCY_CODE CHAR(3) NOT NULL,
    EXPECTED_COUNT NUMBER(19) NOT NULL,
    ACTUAL_COUNT NUMBER(19) NOT NULL,
    EXPECTED_TOTAL NUMBER(19,4) NOT NULL,
    ACTUAL_TOTAL NUMBER(19,4) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    VERSION_NO NUMBER(19) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_FIN_RECON_RUN PRIMARY KEY (RUN_ID),
    CONSTRAINT UQ_FIN_RECON_RUN UNIQUE (EOD_RUN_ID, CURRENCY_CODE),
    CONSTRAINT CK_FIN_RECON_STATUS CHECK (STATUS IN ('MATCHED','EXCEPTION','RESOLVED'))
);

CREATE TABLE FIN_RECON_ITEM (
    ITEM_ID VARCHAR2(36) NOT NULL,
    RUN_ID VARCHAR2(36) NOT NULL,
    REFERENCE VARCHAR2(160) NOT NULL,
    EXPECTED_AMOUNT NUMBER(19,4) NOT NULL,
    ACTUAL_AMOUNT NUMBER(19,4) NOT NULL,
    DIFFERENCE NUMBER(19,4) NOT NULL,
    BLOCKING_FLAG NUMBER(1) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    RESOLUTION VARCHAR2(1000),
    RESOLVED_BY VARCHAR2(100),
    RESOLVED_AT TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT PK_FIN_RECON_ITEM PRIMARY KEY (ITEM_ID),
    CONSTRAINT FK_FIN_RECON_RUN FOREIGN KEY (RUN_ID) REFERENCES FIN_RECON_RUN(RUN_ID),
    CONSTRAINT CK_FIN_RECON_BLOCKING CHECK (BLOCKING_FLAG IN (0,1)),
    CONSTRAINT CK_FIN_RECON_ITEM_STATUS CHECK (STATUS IN ('OPEN','RESOLVED','ACCEPTED'))
);
