UPDATE GL_ACCOUNT
SET NAME = 'Merchant payable awaiting settlement', STATUS = 'ACTIVE', VERSION_NO = VERSION_NO + 1
WHERE GL_CODE = 'MERCHANT_PAYABLE';

UPDATE GL_ACCOUNT
SET NAME = 'Reserved for a future settlement workflow'
WHERE GL_CODE = 'SETTLEMENT_PAYABLE';

INSERT INTO SUBLEDGER_MAPPING (
    MAPPING_ID,
    MAPPING_CODE,
    PRODUCT_CODE,
    CURRENCY_CODE,
    GL_CODE,
    EFFECTIVE_FROM,
    EFFECTIVE_TO,
    STATUS,
    CREATED_AT
) VALUES (
    '10000000-0000-0000-0000-000000000009',
    'MERCHANT_PAYABLE',
    NULL,
    'INR',
    'MERCHANT_PAYABLE',
    DATE '2020-01-01',
    NULL,
    'ACTIVE',
    CURRENT_TIMESTAMP
);

INSERT INTO ACCOUNTING_RULE (
    RULE_ID,
    RULE_CODE,
    EVENT_TYPE,
    COMPONENT_TYPE,
    PRODUCT_CODE,
    CURRENCY_CODE,
    RULE_VERSION,
    DEBIT_MAPPING_CODE,
    CREDIT_MAPPING_CODE,
    EFFECTIVE_FROM,
    EFFECTIVE_TO,
    STATUS,
    CREATED_AT
) VALUES (
    '20000000-0000-0000-0000-000000000012',
    'CREDIT_CARD_MERCHANT_PAYMENT_PRINCIPAL',
    'CREDIT_CARD_MERCHANT_PAYMENT',
    'PRINCIPAL',
    NULL,
    'INR',
    1,
    'CARD_RECEIVABLE',
    'MERCHANT_PAYABLE',
    DATE '2020-01-01',
    NULL,
    'ACTIVE',
    CURRENT_TIMESTAMP
);
