--liquibase formatted sql

--changeset moneybags:accounting-004
CREATE TABLE FIN_RECON_RUN (
    RUN_ID VARCHAR2(36) NOT NULL,
    EOD_RUN_ID VARCHAR2(80) NOT NULL,
    BUSINESS_DATE DATE NOT NULL,
    CURRENCY_CODE CHAR(3) NOT NULL,
    EXPECTED_COUNT NUMBER(19) NOT NULL,
    ACTUAL_COUNT NUMBER(19) NOT NULL,
    EXPECTED_TOTAL NUMBER(19,4) NOT NULL,
    ACTUAL_TOTAL NUMBER(19,4) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    VERSION_NO NUMBER(19) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_FIN_RECON_RUN PRIMARY KEY (RUN_ID),
    CONSTRAINT UQ_FIN_RECON_RUN UNIQUE (EOD_RUN_ID, CURRENCY_CODE),
    CONSTRAINT CK_FIN_RECON_STATUS CHECK (STATUS IN ('MATCHED','EXCEPTION','RESOLVED'))
);

CREATE TABLE FIN_RECON_ITEM (
    ITEM_ID VARCHAR2(36) NOT NULL,
    RUN_ID VARCHAR2(36) NOT NULL,
    REFERENCE VARCHAR2(160) NOT NULL,
    EXPECTED_AMOUNT NUMBER(19,4) NOT NULL,
    ACTUAL_AMOUNT NUMBER(19,4) NOT NULL,
    DIFFERENCE NUMBER(19,4) NOT NULL,
    BLOCKING_FLAG NUMBER(1) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    RESOLUTION VARCHAR2(1000),
    RESOLVED_BY VARCHAR2(100),
    RESOLVED_AT TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT PK_FIN_RECON_ITEM PRIMARY KEY (ITEM_ID),
    CONSTRAINT FK_FIN_RECON_RUN FOREIGN KEY (RUN_ID) REFERENCES FIN_RECON_RUN(RUN_ID),
    CONSTRAINT CK_FIN_RECON_BLOCKING CHECK (BLOCKING_FLAG IN (0,1)),
    CONSTRAINT CK_FIN_RECON_ITEM_STATUS CHECK (STATUS IN ('OPEN','RESOLVED','ACCEPTED'))
);
