--liquibase formatted sql

--changeset moneybags:accounting-006
CREATE TABLE TRIAL_BALANCE_RUN (
    RUN_ID VARCHAR2(36) NOT NULL,
    BUSINESS_DATE DATE NOT NULL,
    CURRENCY_CODE CHAR(3) NOT NULL,
    TOTAL_DEBIT NUMBER(19,4) NOT NULL,
    TOTAL_CREDIT NUMBER(19,4) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    GENERATED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    VERSION_NO NUMBER(19) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_TRIAL_BALANCE_RUN PRIMARY KEY (RUN_ID),
    CONSTRAINT UQ_TRIAL_BALANCE_RUN UNIQUE (BUSINESS_DATE, CURRENCY_CODE),
    CONSTRAINT CK_TRIAL_BALANCE_STATUS CHECK (STATUS IN ('BALANCED','IMBALANCED'))
);

CREATE TABLE TRIAL_BALANCE_LINE (
    LINE_ID VARCHAR2(36) NOT NULL,
    RUN_ID VARCHAR2(36) NOT NULL,
    GL_CODE VARCHAR2(40) NOT NULL,
    DEBIT_TOTAL NUMBER(19,4) NOT NULL,
    CREDIT_TOTAL NUMBER(19,4) NOT NULL,
    CLOSING_BALANCE NUMBER(19,4) NOT NULL,
    CONSTRAINT PK_TRIAL_BALANCE_LINE PRIMARY KEY (LINE_ID),
    CONSTRAINT FK_TRIAL_BALANCE_RUN FOREIGN KEY (RUN_ID) REFERENCES TRIAL_BALANCE_RUN(RUN_ID),
    CONSTRAINT FK_TRIAL_BALANCE_GL FOREIGN KEY (GL_CODE) REFERENCES GL_ACCOUNT(GL_CODE),
    CONSTRAINT UQ_TRIAL_BALANCE_LINE UNIQUE (RUN_ID, GL_CODE)
);
