CREATE TABLE ACCT_GL_ACCOUNT (
    GL_ACCOUNT_ID VARCHAR2(36) NOT NULL,
    GL_CODE VARCHAR2(40) NOT NULL,
    NAME VARCHAR2(160) NOT NULL,
    ACCOUNT_TYPE VARCHAR2(20) NOT NULL,
    NORMAL_BALANCE VARCHAR2(10) NOT NULL,
    CURRENCY_CODE CHAR(3) NOT NULL,
    PARENT_GL_CODE VARCHAR2(40),
    STATUS VARCHAR2(20) NOT NULL,
    VERSION_NO NUMBER(19) DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT PK_ACCT_GL_ACCOUNT PRIMARY KEY (GL_ACCOUNT_ID),
    CONSTRAINT UQ_ACCT_GL_ACCOUNT_CODE UNIQUE (GL_CODE),
    CONSTRAINT CK_ACCT_GL_ACCOUNT_TYPE CHECK (ACCOUNT_TYPE IN ('ASSET','LIABILITY','EQUITY','INCOME','EXPENSE')),
    CONSTRAINT CK_ACCT_GL_NORMAL_BALANCE CHECK (NORMAL_BALANCE IN ('DEBIT','CREDIT')),
    CONSTRAINT CK_ACCT_GL_STATUS CHECK (STATUS IN ('ACTIVE','INACTIVE'))
);

CREATE TABLE ACCT_ACCOUNTING_RULE (
    RULE_ID VARCHAR2(36) NOT NULL,
    RULE_CODE VARCHAR2(60) NOT NULL,
    EVENT_TYPE VARCHAR2(60) NOT NULL,
    COMPONENT_TYPE VARCHAR2(40) NOT NULL,
    PRODUCT_CODE VARCHAR2(40),
    CURRENCY_CODE CHAR(3) NOT NULL,
    RULE_VERSION NUMBER(10) NOT NULL,
    DEBIT_MAPPING_CODE VARCHAR2(60) NOT NULL,
    CREDIT_MAPPING_CODE VARCHAR2(60) NOT NULL,
    EFFECTIVE_FROM DATE NOT NULL,
    EFFECTIVE_TO DATE,
    STATUS VARCHAR2(20) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT PK_ACCT_ACCOUNTING_RULE PRIMARY KEY (RULE_ID),
    CONSTRAINT UQ_ACCT_RULE_VERSION UNIQUE (RULE_CODE, RULE_VERSION),
    CONSTRAINT CK_ACCT_RULE_STATUS CHECK (STATUS IN ('ACTIVE','INACTIVE')),
    CONSTRAINT CK_ACCT_RULE_DATES CHECK (EFFECTIVE_TO IS NULL OR EFFECTIVE_TO >= EFFECTIVE_FROM)
);
CREATE INDEX IX_ACCT_RULE_RESOLUTION ON ACCT_ACCOUNTING_RULE(EVENT_TYPE, COMPONENT_TYPE, CURRENCY_CODE, STATUS);

CREATE TABLE ACCT_SUBLEDGER_MAPPING (
    MAPPING_ID VARCHAR2(36) NOT NULL,
    MAPPING_CODE VARCHAR2(60) NOT NULL,
    PRODUCT_CODE VARCHAR2(40),
    CURRENCY_CODE CHAR(3) NOT NULL,
    GL_CODE VARCHAR2(40) NOT NULL,
    EFFECTIVE_FROM DATE NOT NULL,
    EFFECTIVE_TO DATE,
    STATUS VARCHAR2(20) NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT PK_ACCT_SUBLEDGER_MAPPING PRIMARY KEY (MAPPING_ID),
    CONSTRAINT FK_ACCT_MAPPING_GL FOREIGN KEY (GL_CODE) REFERENCES ACCT_GL_ACCOUNT(GL_CODE),
    CONSTRAINT UQ_ACCT_SUBLEDGER_MAPPING UNIQUE (MAPPING_CODE, PRODUCT_CODE, CURRENCY_CODE, EFFECTIVE_FROM),
    CONSTRAINT CK_ACCT_MAPPING_STATUS CHECK (STATUS IN ('ACTIVE','INACTIVE')),
    CONSTRAINT CK_ACCT_MAPPING_DATES CHECK (EFFECTIVE_TO IS NULL OR EFFECTIVE_TO >= EFFECTIVE_FROM)
);
CREATE INDEX IX_ACCT_MAPPING_RESOLUTION ON ACCT_SUBLEDGER_MAPPING(MAPPING_CODE, CURRENCY_CODE, STATUS);

CREATE TABLE ACCT_SUBLEDGER_ACCOUNT (
    SUBLEDGER_ACCOUNT_ID VARCHAR2(36) NOT NULL,
    ACCOUNT_TYPE VARCHAR2(30) NOT NULL,
    ACCOUNT_REFERENCE VARCHAR2(100) NOT NULL,
    PRODUCT_CODE VARCHAR2(40),
    CURRENCY_CODE CHAR(3) NOT NULL,
    LIFECYCLE_STATE VARCHAR2(20) NOT NULL,
    SOURCE_SERVICE VARCHAR2(80) NOT NULL,
    OPENED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CLOSED_AT TIMESTAMP(6) WITH TIME ZONE,
    VERSION_NO NUMBER(19) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_ACCT_SUBLEDGER_ACCOUNT PRIMARY KEY (SUBLEDGER_ACCOUNT_ID),
    CONSTRAINT UQ_ACCT_SUBLEDGER_ACCOUNT UNIQUE (ACCOUNT_TYPE, ACCOUNT_REFERENCE),
    CONSTRAINT CK_ACCT_SUBLEDGER_TYPE CHECK (ACCOUNT_TYPE IN ('DEPOSIT_ACCOUNT','CREDIT_CARD_ACCOUNT')),
    CONSTRAINT CK_ACCT_SUBLEDGER_STATE CHECK (LIFECYCLE_STATE IN ('OPEN','CLOSED'))
);
CREATE INDEX IX_ACCT_SUBLEDGER_REF ON ACCT_SUBLEDGER_ACCOUNT(ACCOUNT_REFERENCE, LIFECYCLE_STATE);

CREATE TABLE ACCT_ACCOUNT_LIFECYCLE_EVENT (
    LIFECYCLE_EVENT_ID VARCHAR2(36) NOT NULL,
    EVENT_REFERENCE VARCHAR2(160) NOT NULL,
    IDEMPOTENCY_KEY_HASH VARCHAR2(64) NOT NULL,
    REQUEST_HASH VARCHAR2(64) NOT NULL,
    EVENT_TYPE VARCHAR2(40) NOT NULL,
    ACCOUNT_TYPE VARCHAR2(30) NOT NULL,
    ACCOUNT_REFERENCE VARCHAR2(100) NOT NULL,
    BUSINESS_DATE DATE NOT NULL,
    OCCURRED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    REASON_CODE VARCHAR2(40),
    SOURCE_SERVICE VARCHAR2(80) NOT NULL,
    CORRELATION_ID VARCHAR2(64) NOT NULL,
    PROCESSED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT PK_ACCT_LIFECYCLE_EVENT PRIMARY KEY (LIFECYCLE_EVENT_ID),
    CONSTRAINT UQ_ACCT_LIFECYCLE_REFERENCE UNIQUE (EVENT_REFERENCE),
    CONSTRAINT UQ_ACCT_LIFECYCLE_IDEM UNIQUE (IDEMPOTENCY_KEY_HASH),
    CONSTRAINT CK_ACCT_LIFECYCLE_TYPE CHECK (ACCOUNT_TYPE IN ('DEPOSIT_ACCOUNT','CREDIT_CARD_ACCOUNT'))
);
CREATE INDEX IX_ACCT_LIFECYCLE_ACCOUNT ON ACCT_ACCOUNT_LIFECYCLE_EVENT(ACCOUNT_TYPE, ACCOUNT_REFERENCE, PROCESSED_AT);

CREATE TABLE ACCT_POSTING_REQUEST (
    POSTING_REQUEST_ID VARCHAR2(36) NOT NULL,
    EXTERNAL_REFERENCE VARCHAR2(160) NOT NULL,
    IDEMPOTENCY_KEY_HASH VARCHAR2(64) NOT NULL,
    REQUEST_HASH VARCHAR2(64) NOT NULL,
    SOURCE_SERVICE VARCHAR2(80) NOT NULL,
    EVENT_TYPE VARCHAR2(60) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    JOURNAL_NUMBER VARCHAR2(60),
    RECEIVED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    COMPLETED_AT TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT PK_ACCT_POSTING_REQUEST PRIMARY KEY (POSTING_REQUEST_ID),
    CONSTRAINT UQ_ACCT_POSTING_EXTERNAL UNIQUE (EXTERNAL_REFERENCE),
    CONSTRAINT UQ_ACCT_POSTING_IDEM UNIQUE (IDEMPOTENCY_KEY_HASH),
    CONSTRAINT CK_ACCT_POSTING_STATUS CHECK (STATUS IN ('RECEIVED','POSTED','REJECTED'))
);

CREATE TABLE ACCT_JOURNAL (
    JOURNAL_ID VARCHAR2(36) NOT NULL,
    JOURNAL_NUMBER VARCHAR2(60) NOT NULL,
    POSTING_SEQUENCE NUMBER(19) NOT NULL,
    EXTERNAL_REFERENCE VARCHAR2(160) NOT NULL,
    SOURCE_SERVICE VARCHAR2(80) NOT NULL,
    EVENT_TYPE VARCHAR2(60) NOT NULL,
    OCCURRED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    BUSINESS_DATE DATE NOT NULL,
    CURRENCY_CODE CHAR(3) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    TOTAL_DEBIT NUMBER(19,4) NOT NULL,
    TOTAL_CREDIT NUMBER(19,4) NOT NULL,
    REVERSES_JOURNAL_NUMBER VARCHAR2(60),
    CORRELATION_ID VARCHAR2(64) NOT NULL,
    POSTED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT PK_ACCT_JOURNAL PRIMARY KEY (JOURNAL_ID),
    CONSTRAINT UQ_ACCT_JOURNAL_NUMBER UNIQUE (JOURNAL_NUMBER),
    CONSTRAINT UQ_ACCT_JOURNAL_SEQUENCE UNIQUE (POSTING_SEQUENCE),
    CONSTRAINT UQ_ACCT_JOURNAL_EXTERNAL UNIQUE (EXTERNAL_REFERENCE),
    CONSTRAINT FK_ACCT_JOURNAL_REVERSAL FOREIGN KEY (REVERSES_JOURNAL_NUMBER) REFERENCES ACCT_JOURNAL(JOURNAL_NUMBER),
    CONSTRAINT CK_ACCT_JOURNAL_STATUS CHECK (STATUS IN ('POSTED')),
    CONSTRAINT CK_ACCT_JOURNAL_BALANCED CHECK (TOTAL_DEBIT = TOTAL_CREDIT),
    CONSTRAINT CK_ACCT_JOURNAL_POSITIVE CHECK (TOTAL_DEBIT > 0)
);
CREATE INDEX IX_ACCT_JOURNAL_SEARCH ON ACCT_JOURNAL(BUSINESS_DATE, SOURCE_SERVICE, EVENT_TYPE);

CREATE TABLE ACCT_JOURNAL_LINE (
    LINE_ID VARCHAR2(36) NOT NULL,
    JOURNAL_ID VARCHAR2(36) NOT NULL,
    LINE_NUMBER NUMBER(10) NOT NULL,
    GL_CODE VARCHAR2(40) NOT NULL,
    SUBLEDGER_REFERENCE VARCHAR2(100),
    COMPONENT_TYPE VARCHAR2(40) NOT NULL,
    RULE_CODE VARCHAR2(60) NOT NULL,
    RULE_VERSION NUMBER(10) NOT NULL,
    DEBIT_AMOUNT NUMBER(19,4) DEFAULT 0 NOT NULL,
    CREDIT_AMOUNT NUMBER(19,4) DEFAULT 0 NOT NULL,
    NARRATION VARCHAR2(500),
    CONSTRAINT PK_ACCT_JOURNAL_LINE PRIMARY KEY (LINE_ID),
    CONSTRAINT FK_ACCT_LINE_JOURNAL FOREIGN KEY (JOURNAL_ID) REFERENCES ACCT_JOURNAL(JOURNAL_ID),
    CONSTRAINT FK_ACCT_LINE_GL FOREIGN KEY (GL_CODE) REFERENCES ACCT_GL_ACCOUNT(GL_CODE),
    CONSTRAINT UQ_ACCT_JOURNAL_LINE UNIQUE (JOURNAL_ID, LINE_NUMBER),
    CONSTRAINT CK_ACCT_JOURNAL_LINE_SIDE CHECK ((DEBIT_AMOUNT > 0 AND CREDIT_AMOUNT = 0) OR (CREDIT_AMOUNT > 0 AND DEBIT_AMOUNT = 0))
);
CREATE INDEX IX_ACCT_LINE_SUBLEDGER ON ACCT_JOURNAL_LINE(SUBLEDGER_REFERENCE);
CREATE INDEX IX_ACCT_LINE_GL ON ACCT_JOURNAL_LINE(GL_CODE);
