CREATE TABLE BANK_USER (
    USER_ID CHAR(36) NOT NULL,
    USERNAME VARCHAR2(100) NOT NULL,
    PASSWORD_HASH VARCHAR2(200) NOT NULL,
    CUSTOMER_ID VARCHAR2(64),
    TENANT_ID VARCHAR2(64) NOT NULL,
    ROLES VARCHAR2(200) NOT NULL,
    ENABLED NUMBER(1) DEFAULT 1 NOT NULL,
    ACCOUNT_NON_LOCKED NUMBER(1) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT PK_BANK_USER PRIMARY KEY (USER_ID),
    CONSTRAINT UK_BANK_USER_USERNAME UNIQUE (USERNAME),
    CONSTRAINT CK_BANK_USER_ENABLED CHECK (ENABLED IN (0, 1)),
    CONSTRAINT CK_BANK_USER_LOCKED CHECK (ACCOUNT_NON_LOCKED IN (0, 1))
)
