import { h } from "preact";
import { useState } from "preact/hooks";
import type { Account, Bill, CardApplication, FixedDeposit, Journal, Kyc, Payment, PaymentEodControl, Product } from "../contracts";
import { EmptyState, ErrorState, Field, Loading, Money, PageHeader, Panel, SelectField, Status, useIdempotencyKeyStore, useRemote } from "../components/common";
import { navigate } from "../router";
import { items, services } from "../services";
import { formatDate } from "../utils";

function Cell({ value }: { value: unknown }) {
  if (typeof value === "number") return <span>{value.toLocaleString("en-IN")}</span>;
  if (typeof value === "boolean") return <span>{value ? "Yes" : "No"}</span>;
  return <span>{String(value ?? "—")}</span>;
}

export function OperationsDashboard() {
  const remote = useRemote(async (signal) => {
    const [kyc, journals] = await Promise.allSettled([services.kyc.queue(signal), services.accounting.journals(signal)]);
    return { kycs: kyc.status === "fulfilled" ? items(kyc.value) : [], journals: journals.status === "fulfilled" ? items(journals.value) : [], unavailable: Number(kyc.status === "rejected") + Number(journals.status === "rejected") };
  }, []);
  if (remote.loading) return <Loading label="Preparing operations overview"/>;
  if (remote.error) return <ErrorState error={remote.error} retry={remote.retry}/>;
  const data = remote.data!;
  return <><PageHeader title="Operations overview" description="Queues and financial controls across MoneyBags."/>{Boolean(data.unavailable)&&<div class="mb-warning-banner">Some operational services are unavailable.</div>}<div class="mb-ops-metrics"><article><span>KYC work queue</span><strong>{data.kycs.length}</strong><small>Cases requiring review</small></article><article><span>Recent journals</span><strong>{data.journals.length}</strong><small>Loaded from Accounting</small></article><article><span>Platform state</span><strong>{data.unavailable?"Degraded":"Online"}</strong><small>{data.unavailable?`${data.unavailable} service request${data.unavailable===1?"":"s"} unavailable`:"Gateway-authenticated session"}</small></article></div><Panel title="Recent accounting journals"><JournalTable values={data.journals.slice(0,6)}/></Panel></>;
}

export function KycWorkQueue() {
  const [revision,setRevision]=useState(0);const remote=useRemote((signal)=>services.kyc.queue(signal),[revision]);const [actionError,setActionError]=useState<unknown>();const [acting,setActing]=useState<number>();const commands=useIdempotencyKeyStore();
  if(remote.loading)return <Loading label="Loading KYC work queue"/>;if(remote.error)return <ErrorState error={remote.error} retry={remote.retry}/>;const records=items(remote.data);
  const decide=async(record:Kyc,decision:"APPROVED"|"REJECTED")=>{const reason=decision==="REJECTED"?window.prompt("Enter the rejection reason")??undefined:undefined;if(decision==="REJECTED"&&!reason)return;if(!window.confirm(`Are you sure you want to ${decision === "APPROVED" ? "approve" : "reject"} KYC ${record.kycId} for ${record.customerName}?`))return;setActing(record.kycId);setActionError(undefined);try{await services.kyc.decide(record.kycId,decision,reason,commands.keyFor({kycId:record.kycId,decision,rejectionReason:reason}));commands.reset();setRevision(n=>n+1);}catch(error){setActionError(error);}finally{setActing(undefined);}};
  return <><PageHeader title="KYC work queue" description="Demo verification uses the customer information captured during CIF onboarding."/>{actionError&&<ErrorState error={actionError}/>}<div class="mb-warning-banner">Physical document upload is disabled for this demo. Review the customer and CIF references, then approve or reject the case.</div><Panel>{records.length?<div class="mb-table-wrap"><table class="mb-table"><thead><tr><th>KYC</th><th>Customer</th><th>Status</th><th>Decision</th><th>Initiated</th><th>Actions</th></tr></thead><tbody>{records.map(record=><tr key={record.kycId}><td>{record.kycId}<small>CIF {record.cifId}</small></td><td>{record.customerName}</td><td><Status value={record.kycStatus}/></td><td>{record.decision??"Pending review"}</td><td>{formatDate(record.initiatedAt)}</td><td><div class="mb-row-actions"><button disabled={acting===record.kycId} onClick={()=>decide(record,"APPROVED")}>Approve</button><button class="is-danger" disabled={acting===record.kycId} onClick={()=>decide(record,"REJECTED")}>Reject</button></div></td></tr>)}</tbody></table></div>:<EmptyState title="Queue is clear" message="There are no KYC cases requiring review."/>}</Panel></>;
}

export function ProductAdministration(){const[revision,setRevision]=useState(0);const[creating,setCreating]=useState(false);const[acting,setActing]=useState("");const[actionError,setActionError]=useState<unknown>();const commands=useIdempotencyKeyStore();const remote=useRemote((signal)=>services.products.all(signal),[revision]);const publish=async(product:Product)=>{if(!window.confirm(`Publish ${product.productName}? Demo terms will be applied where they are missing.`))return;setActing(product.productCode);setActionError(undefined);try{const body=publishableProduct(product);await services.products.update(product.productCode,body,commands.keyFor({productCode:product.productCode,action:"publish-terms"}));commands.reset();await services.products.changeStatus(product.productCode,"ACTIVE",commands.keyFor({productCode:product.productCode,action:"publish-status"}));commands.reset();setRevision(value=>value+1);}catch(error){setActionError(error);}finally{setActing("");}};if(remote.loading)return <Loading label="Loading product catalogue"/>;if(remote.error)return <ErrorState error={remote.error} retry={remote.retry}/>;const products=items(remote.data);return <><PageHeader title="Product administration" description="Create draft products and publish them to the customer catalogue." action={<button class="mb-button mb-button-primary" onClick={()=>setCreating(value=>!value)}>{creating?"Close form":"Add product"}</button>}/>{actionError&&<ErrorState error={actionError}/>} {creating&&<ProductCreateForm onCreated={()=>{setCreating(false);setRevision(value=>value+1);}}/>}<Panel title="Catalogue products">{products.length?<div class="mb-table-wrap"><table class="mb-table"><thead><tr><th>Product</th><th>Category</th><th>Subtype</th><th>Currency</th><th>Status</th><th>Version</th><th>Action</th></tr></thead><tbody>{products.map((p:Product)=><tr key={p.productCode}><td><strong>{p.productName}</strong><small>{p.productCode}</small></td><td>{p.category}</td><td>{p.subtype?.replaceAll("_"," ")}</td><td>{p.currencyCode}</td><td><Status value={p.status}/></td><td>{p.version}</td><td>{p.status==="DRAFT"&&p.subtype!=="FIXED_DEPOSIT"?<button class="mb-button mb-button-primary" disabled={acting===p.productCode} onClick={()=>publish(p)}>{acting===p.productCode?"Publishing…":"Publish"}</button>:<span>{p.status==="ACTIVE"?"Published":"No action"}</span>}</td></tr>)}</tbody></table></div>:<EmptyState title="No products to show" message="Product Master has not returned any catalogue records."/>}</Panel></>}

function publishableProduct(product:Product){const effectiveFrom=product.effectiveFrom||new Date().toISOString().slice(0,10);const interest=product.interestRule??{annualInterestRate:product.category==="CREDIT_CARD"?36:0,pricingMode:"FIXED",effectiveFrom,interestCalculationMethod:product.category==="CREDIT_CARD"?"DAILY":"DAILY_BALANCE",interestCalculationFrequency:"DAILY",interestPostingFrequency:"MONTHLY",compoundingFrequency:"MONTHLY",dayCountConvention:"ACTUAL_365",rateApplicationMethod:"BOOKING_DATE",interestType:product.category==="CREDIT_CARD"?"DEBIT":"CREDIT"};const closure=product.accountClosureRule??{closureAllowed:true,closureMode:"CUSTOMER_REQUEST",minimumAccountAgeDays:0,noticePeriodDays:0,closureFeeApplicable:false,closureFeeWaiverAfterDays:0,zeroBalanceRequired:true,activeReservationsAllowed:false,activeMandatesAllowed:false,negativeBalanceAllowed:false,pendingChargesMustBeSettled:true,allowedClosureChannels:["WEB"],settlementMethods:["TRANSFER"],approvalRequired:false,effectiveFrom,policyVersion:"V1"};const card=product.creditCardRule??{effectiveFrom,minimumCreditLimit:25000,maximumCreditLimit:250000,interestFreeDays:30,minimumPaymentPercentage:5,minimumPaymentAmount:500,paymentDueDays:15,cashAdvanceAllowed:false};return{productCode:product.productCode,productName:product.productName,description:product.description,category:product.category,subtype:product.subtype,currencyCode:product.currencyCode,effectiveFrom,effectiveTo:product.effectiveTo,changedBy:"bank-admin",interestRule:interest,amountRule:product.amountRule,creditCardRule:product.category==="CREDIT_CARD"?card:undefined,fixedDepositRule:product.fixedDepositRule,interestRateSlabs:product.interestRateSlabs,accountClosureRule:product.category==="DEPOSIT"?closure:undefined,prematureClosureRule:product.prematureClosureRule,renewalRule:product.renewalRule,fees:product.fees,eligibilityRules:product.eligibilityRules,features:product.features};}

function ProductCreateForm({onCreated}:{onCreated:()=>void}){
  const[values,setValues]=useState({productCode:"",productName:"",description:"",subtype:"SAVINGS",currencyCode:"INR",minimumOpeningBalance:"0",minimumAge:"18",minimumMonthlyIncome:"",customerType:"INDIVIDUAL"});
  const[busy,setBusy]=useState(false);const[error,setError]=useState<unknown>();const commands=useIdempotencyKeyStore();
  const set=(key:keyof typeof values)=>(value:string)=>setValues(current=>({...current,[key]:value}));
  const category=values.subtype==="CREDIT_CARD"?"CREDIT_CARD":"DEPOSIT";
  const submit=async(event:Event)=>{event.preventDefault();setBusy(true);setError(undefined);try{const amount=Number(values.minimumOpeningBalance||0);const minimumIncome=values.minimumMonthlyIncome.trim()?Number(values.minimumMonthlyIncome):undefined;const body={productCode:values.productCode.trim().toUpperCase(),productName:values.productName.trim(),description:values.description.trim()||undefined,category,subtype:values.subtype,currencyCode:values.currencyCode.toUpperCase(),effectiveFrom:new Date().toISOString().slice(0,10),changedBy:"bank-admin",amountRule:category==="DEPOSIT"?{minimumOpeningBalance:amount,minimumBalance:0,overdraftAllowed:false,overdraftLimit:0}:undefined,eligibilityRules:[{minimumAge:Number(values.minimumAge||0),minimumMonthlyIncome:minimumIncome,customerType:values.customerType,kycRequired:true,collateralRequired:false,active:true}]};await services.products.create(body,commands.keyFor(body));commands.reset();onCreated();}catch(reason){setError(reason);}finally{setBusy(false);}};
  return <Panel title="Add a product draft" className="mb-product-admin-form"><p class="mb-panel-intro">Draft products are visible only to bank operations. Configure any remaining pricing or policy details before activating a product for customers.</p><form class="mb-form" onSubmit={submit}>{error&&<ErrorState error={error}/>}<div class="mb-form-grid"><Field label="Product code" name="productCode" value={values.productCode} required pattern="[A-Za-z0-9-]+" title="Use letters, numbers and hyphens only" placeholder="e.g. SAV-PLUS-001" onInput={set("productCode")}/><Field label="Product name" name="productName" value={values.productName} required placeholder="e.g. Savings Plus Account" onInput={set("productName")}/></div><Field label="Description" name="description" value={values.description} placeholder="A short customer-facing description" onInput={set("description")}/><div class="mb-form-grid"><SelectField label="Product type" value={values.subtype} required onChange={set("subtype")}><option value="SAVINGS">Savings account</option><option value="CURRENT">Current account</option><option value="CREDIT_CARD">Credit card</option></SelectField><SelectField label="Eligible customer type" value={values.customerType} required onChange={set("customerType")}><option value="INDIVIDUAL">Individual</option><option value="BUSINESS">Business</option><option value="ANY">Any customer type</option></SelectField></div><div class="mb-form-grid"><Field label="Minimum age" name="minimumAge" type="number" min="0" value={values.minimumAge} required onInput={set("minimumAge")}/><Field label="Minimum monthly income (optional)" name="minimumMonthlyIncome" type="number" min="0" value={values.minimumMonthlyIncome} onInput={set("minimumMonthlyIncome")}/></div>{category==="DEPOSIT"&&<Field label="Minimum opening balance" name="minimumOpeningBalance" type="number" min="0" step="0.01" value={values.minimumOpeningBalance} required onInput={set("minimumOpeningBalance")}/>}<div class="mb-draft-note"><strong>What happens next</strong><span>The product will be created as a <b>DRAFT</b>. It will not appear in the customer catalogue until its terms are configured and it is activated. Fixed deposits need their separate rate-slab and maturity-policy setup.</span></div><button class="mb-button mb-button-primary" disabled={busy}>{busy?"Creating draft…":"Create product draft"}</button></form></Panel>;
}

export function JournalSearch(){const remote=useRemote((signal)=>services.accounting.journals(signal),[]);if(remote.loading)return <Loading label="Loading journals"/>;if(remote.error)return <ErrorState error={remote.error} retry={remote.retry}/>;return <><PageHeader title="Journal search" description="Posted financial events and their accounting lines."/><Panel><JournalTable values={items(remote.data)}/></Panel></>}

function JournalTable({values}:{values:Journal[]}){if(!values.length)return <EmptyState title="No journals found" message="Posted journals will appear here."/>;return <div class="mb-table-wrap"><table class="mb-table"><thead><tr><th>Journal</th><th>Source</th><th>Event</th><th>Business date</th><th>Status</th><th>Debit</th><th>Credit</th></tr></thead><tbody>{values.map(j=><tr key={j.journalNumber}><td><strong>{j.journalNumber}</strong><small>{j.externalReference}</small></td><td>{j.sourceService}</td><td>{j.eventType}</td><td>{j.businessDate}</td><td><Status value={j.status}/></td><td><Money value={j.totalDebit} currency={j.currencyCode}/></td><td><Money value={j.totalCredit} currency={j.currencyCode}/></td></tr>)}</tbody></table></div>}

export function AccountingCollection({kind}:{kind:"gl"|"rules"|"mappings"}){const definition=kind==="gl"?{title:"GL accounts",description:"Chart of accounts and lifecycle status.",load:services.accounting.glAccounts}:kind==="rules"?{title:"Accounting rules",description:"Effective posting rules and debit/credit mappings.",load:services.accounting.rules}:{title:"Subledger mappings",description:"Product and currency mappings to general-ledger accounts.",load:services.accounting.mappings};const remote=useRemote((signal)=>definition.load(signal),[kind]);if(remote.loading)return <Loading label={`Loading ${definition.title.toLowerCase()}`}/>;if(remote.error)return <ErrorState error={remote.error} retry={remote.retry}/>;const rows=items(remote.data);const keys=rows.length?Object.keys(rows[0]).filter(key=>!["version"].includes(key)).slice(0,7):[];const action=kind==="rules"?<button class="mb-button mb-button-secondary" onClick={()=>navigate("/ops/accounting/mappings")}>View subledger mappings</button>:kind==="mappings"?<button class="mb-button mb-button-secondary" onClick={()=>navigate("/ops/accounting/rules")}>View accounting rules</button>:undefined;return <><PageHeader title={definition.title} description={definition.description} action={action}/><Panel>{rows.length?<div class="mb-table-wrap"><table class="mb-table"><thead><tr>{keys.map(key=><th key={key}>{key.replace(/([A-Z])/g," $1")}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={index}>{keys.map(key=><td key={key}><Cell value={row[key]}/></td>)}</tr>)}</tbody></table></div>:<EmptyState title={`No ${definition.title.toLowerCase()}`} message="No configuration records are currently available."/>}</Panel></>}

export function DepositOperations(){
  const[revision,setRevision]=useState(0);const[actionError,setActionError]=useState<unknown>();const[acting,setActing]=useState("");const commands=useIdempotencyKeyStore();
  const remote=useRemote((signal)=>Promise.all([services.accounts.all(signal),services.fixedDeposits.all(signal)]),[revision]);
  if(remote.loading)return <Loading label="Loading deposit portfolio"/>;if(remote.error)return <ErrorState error={remote.error} retry={remote.retry}/>;
  const accounts=items<Account>(remote.data?.[0]);const deposits=items<FixedDeposit>(remote.data?.[1]);
  const activate=async(account:Account)=>{if(!window.confirm(`Activate deposit account ${account.maskedAccountNumber||account.accountId}?`))return;setActing(account.accountId);setActionError(undefined);try{const detail=await services.accounts.one(account.accountId);const body={reasonCode:"ACCOUNT_OPENING_APPROVED",reasonText:"Approved by bank operations"};await services.accounts.command(account.accountId,"activate",detail.version,body,commands.keyFor({accountId:account.accountId,action:"activate"}));commands.reset();setRevision(value=>value+1);}catch(error){setActionError(error);}finally{setActing("");}};
  return <><PageHeader title="Deposit operations" description="Review and activate customer account-opening requests."/>{actionError&&<ErrorState error={actionError}/>}<Panel title="Deposit accounts">{accounts.length?<div class="mb-table-wrap"><table class="mb-table"><thead><tr><th>Account</th><th>Product</th><th>Status</th><th>Currency</th><th>Available balance</th><th>Branch</th><th>Action</th></tr></thead><tbody>{accounts.map(account=><tr key={account.accountId}><td><strong>{account.maskedAccountNumber||account.accountId}</strong><small>{account.accountId}</small></td><td>{account.productName}</td><td><Status value={account.status}/></td><td>{account.currency}</td><td><Money value={account.availableBalance} currency={account.currency}/></td><td>{account.servicingBranchId??"—"}</td><td>{account.status==="PENDING_ACTIVATION"?<button class="mb-button mb-button-primary" disabled={acting===account.accountId} onClick={()=>activate(account)}>{acting===account.accountId?"Activating…":"Approve & activate"}</button>:<span>No approval required</span>}</td></tr>)}</tbody></table></div>:<EmptyState title="No deposit accounts to show" message="Customer account requests will appear here."/>}</Panel><Panel title="Fixed deposits">{deposits.length?<div class="mb-table-wrap"><table class="mb-table"><thead><tr><th>Deposit</th><th>Product</th><th>Status</th><th>Principal</th><th>Rate</th><th>Maturity</th></tr></thead><tbody>{deposits.map(fd=><tr key={fd.fixedDepositId}><td><strong>{fd.maskedAccountNumber||fd.fixedDepositId}</strong><small>{fd.fixedDepositId}</small></td><td>{fd.productCode}</td><td><Status value={fd.status}/></td><td><Money value={fd.principal} currency={fd.currency}/></td><td>{fd.annualInterestRate}%</td><td>{formatDate(fd.maturityDate)}</td></tr>)}</tbody></table></div>:<EmptyState title="No fixed deposits to show" message="No fixed-deposit records are currently available."/>}</Panel></>;
}

export function CardBillingOperations(){
  const[revision,setRevision]=useState(0);
  const[actionError,setActionError]=useState<unknown>();
  const[acting,setActing]=useState<number>();
  const commands=useIdempotencyKeyStore();
  const remote=useRemote(async signal=>{
    const[applications,bills]=await Promise.allSettled([services.cards.applicationsForReview(undefined,signal),services.bills.list(undefined,signal)]);
    return{applications:applications.status==="fulfilled"?applications.value:[],bills:bills.status==="fulfilled"?items<Bill>(bills.value):[],unavailable:Number(applications.status==="rejected")+Number(bills.status==="rejected")};
  },[revision]);
  if(remote.loading)return <Loading label="Loading card operations"/>;
  if(remote.error)return <ErrorState error={remote.error} retry={remote.retry}/>;
  const data=remote.data!;
  const decide=async(application:CardApplication,decision:"APPROVE"|"REJECT")=>{
    if(!window.confirm(`${decision==="APPROVE"?"Approve":"Reject"} card application ${application.applicationId}?`))return;
    setActing(application.applicationId);setActionError(undefined);
    try{const key=commands.keyFor({applicationId:application.applicationId,decision});if(decision==="APPROVE")await services.cards.approve(application.applicationId,key);else await services.cards.reject(application.applicationId,key);commands.reset();setRevision(value=>value+1);}catch(error){setActionError(error);}finally{setActing(undefined);}
  };
  return <><PageHeader title="Cards & billing operations" description="Review card applications, approve eligible customers and monitor generated bills."/>{actionError&&<ErrorState error={actionError}/>} {Boolean(data.unavailable)&&<div class="mb-warning-banner">Some card or billing information is temporarily unavailable.</div>}<Panel title="Credit-card applications">{data.applications.length?<div class="mb-table-wrap"><table class="mb-table"><thead><tr><th>Application</th><th>CIF</th><th>Product</th><th>Requested limit</th><th>Eligibility</th><th>Status</th><th>Actions</th></tr></thead><tbody>{data.applications.map((application:CardApplication)=><tr key={application.applicationId}><td><strong>{application.applicationId}</strong><small>{formatDate(application.submittedAt)}</small></td><td>{application.cifId}</td><td>{application.productCode}</td><td><Money value={application.requestedCreditLimit}/></td><td><Status value={application.eligibilityStatus}/></td><td><Status value={application.applicationStatus}/></td><td>{application.applicationStatus==="PENDING"?<div class="mb-row-actions"><button disabled={acting===application.applicationId||application.eligibilityStatus!=="ELIGIBLE"} title={application.eligibilityStatus!=="ELIGIBLE"?"Only eligible applications can be approved":undefined} onClick={()=>decide(application,"APPROVE")}>Approve</button><button class="is-danger" disabled={acting===application.applicationId} onClick={()=>decide(application,"REJECT")}>Reject</button></div>:"Decision complete"}</td></tr>)}</tbody></table></div>:<EmptyState title="No card applications" message="Customer applications will appear here for review."/>}</Panel><Panel title="Generated bills">{data.bills.length?<div class="mb-table-wrap"><table class="mb-table"><thead><tr><th>Bill</th><th>Card account</th><th>Period</th><th>Status</th><th>Outstanding</th><th>Due date</th></tr></thead><tbody>{data.bills.map((bill:Bill)=><tr key={bill.billId}><td><strong>{bill.billId}</strong></td><td>{bill.accountId}</td><td>{bill.billingPeriod}</td><td><Status value={bill.status}/></td><td><Money value={bill.outstandingAmount} currency={bill.currency}/></td><td>{formatDate(bill.paymentDueDate)}</td></tr>)}</tbody></table></div>:<EmptyState title="No bills to show" message="Generated card bills will appear here."/>}</Panel></>;
}

const paymentStatuses=['PENDING_VALIDATION','PENDING_RESERVATION','PENDING_ACCOUNTING','PENDING_SETTLEMENT','PENDING_BILLING','SETTLED','FAILED','CANCELLED','REVERSAL_PENDING','REVERSED'];

export function PaymentOperations(){
  const today=new Date().toISOString().slice(0,10);const[status,setStatus]=useState('');const[businessDate,setBusinessDate]=useState(today);const[revision,setRevision]=useState(0);const[actionError,setActionError]=useState<unknown>();const[acting,setActing]=useState('');const[control,setControl]=useState<PaymentEodControl>();const commands=useIdempotencyKeyStore();
  const remote=useRemote(signal=>services.paymentOperations.list(status||undefined,businessDate||undefined,signal),[status,businessDate,revision]);
  if(remote.loading)return <Loading label="Loading payment operations"/>;if(remote.error)return <ErrorState error={remote.error} retry={remote.retry}/>;const payments=items<Payment>(remote.data);
  const eod=async(action:'cutoff'|'drain'|'reopen')=>{if(action==='cutoff'&&!window.confirm(`Stop new payment intake for ${businessDate}?`))return;setActing(action);setActionError(undefined);try{const key=commands.keyFor({action,businessDate});const result=action==='cutoff'?await services.paymentOperations.cutoff(businessDate,key):action==='drain'?await services.paymentOperations.drain(key):await services.paymentOperations.reopen(key);setControl(result);commands.reset();setRevision(value=>value+1);}catch(error){setActionError(error);}finally{setActing('');}};
  const recover=async(payment:Payment,action:'reversal'|'billing')=>{const reason=action==='reversal'?window.prompt('Reason for retrying this reversal','Complete pending payment compensation'):undefined;if(action==='reversal'&&!reason)return;setActing(payment.paymentId);setActionError(undefined);try{const key=commands.keyFor({paymentId:payment.paymentId,action,reason});if(action==='reversal')await services.paymentOperations.reverse(payment.paymentId,reason!,key);else await services.paymentOperations.retryBilling(payment.paymentId,key);commands.reset();setRevision(value=>value+1);}catch(error){setActionError(error);}finally{setActing('');}};
  return <><PageHeader title="Payment operations" description="Search payment lifecycles, control EOD intake and recover incomplete settlements."/>{actionError&&<ErrorState error={actionError}/>}<Panel title="Business-day controls"><div class="mb-filter-row"><label class="mb-field"><span>Business date</span><input type="date" value={businessDate} onInput={event=>setBusinessDate((event.currentTarget as HTMLInputElement).value)}/></label><label class="mb-field"><span>Payment status</span><select value={status} onChange={event=>setStatus((event.currentTarget as HTMLSelectElement).value)}><option value="">All statuses</option>{paymentStatuses.map(value=><option value={value}>{value.replaceAll('_',' ')}</option>)}</select></label><button class="mb-button mb-button-secondary" disabled={Boolean(acting)} onClick={()=>eod('cutoff')}>Cut off intake</button><button class="mb-button mb-button-secondary" disabled={Boolean(acting)} onClick={()=>eod('drain')}>Check drain</button><button class="mb-button mb-button-primary" disabled={Boolean(acting)} onClick={()=>eod('reopen')}>Reopen intake</button></div>{control&&<div class={control.newPaymentIntake?'mb-success-banner':'mb-warning-banner'}><strong>{control.status.replaceAll('_',' ')}</strong> · {control.pendingPayments} payment{control.pendingPayments===1?'':'s'} still in flight · intake {control.newPaymentIntake?'open':'closed'}</div>}</Panel><Panel title={`Payments (${payments.length})`}>{payments.length?<div class="mb-table-wrap"><table class="mb-table"><thead><tr><th>Payment</th><th>Customer</th><th>Type</th><th>Status</th><th>Business date</th><th>Amount</th><th>Recovery</th></tr></thead><tbody>{payments.map(payment=><tr key={payment.paymentId}><td><strong>{payment.reference??payment.paymentId}</strong><small>{payment.paymentId}</small></td><td>{payment.requestorCustomerId}</td><td>{payment.paymentType.replaceAll('_',' ')}</td><td><Status value={payment.status}/></td><td>{formatDate(payment.businessDate)}</td><td><Money value={payment.amount} currency={payment.currencyCode}/></td><td>{payment.status==='REVERSAL_PENDING'?<button class="mb-button mb-button-secondary" disabled={acting===payment.paymentId} onClick={()=>recover(payment,'reversal')}>Retry reversal</button>:payment.status==='PENDING_BILLING'?<button class="mb-button mb-button-secondary" disabled={acting===payment.paymentId} onClick={()=>recover(payment,'billing')}>Retry billing</button>:<span>No action required</span>}</td></tr>)}</tbody></table></div>:<EmptyState title="No payments found" message="No payment records match the selected business date and status."/>}</Panel></>;
}

export function OperationsPlaceholder({title,description,blocker}:{title:string;description:string;blocker:string}){return <><PageHeader title={title} description={description}/><Panel><div class="mb-warning-banner">{blocker}</div><EmptyState title="Backend contract required" message="The operations route is implemented and will activate when its public, admin-scoped API is available."/></Panel></>}
