package com.moneybags.payments.domain;

public enum PaymentType {
  BOOK_TRANSFER,
  CREDIT_CARD_MERCHANT_PAYMENT,
  CREDIT_CARD_REPAYMENT,
  FIXED_DEPOSIT_FUNDING,
  FIXED_DEPOSIT_MATURITY_PAYOUT,
  FIXED_DEPOSIT_PREMATURE_PAYOUT
}
