--liquibase formatted sql

--changeset devansh:001

CREATE TABLE kyc
(
    kyc_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- CIF customer snapshot
    cif_id NUMBER NOT NULL,
    customer_name VARCHAR2(200) NOT NULL,
    date_of_birth DATE,
    mobile_number VARCHAR2(20),
    email VARCHAR2(255),
    pan_number VARCHAR2(20),
    aadhaar_number VARCHAR2(20),
    address_line1 VARCHAR2(500),
    address_line2 VARCHAR2(500),
    city VARCHAR2(100),
    state VARCHAR2(100),
    postal_code VARCHAR2(20),
    country VARCHAR2(100),

    -- KYC workflow
    kyc_status VARCHAR2(20) NOT NULL,
    decision VARCHAR2(20),
    rejection_reason CLOB,
    mismatch_reason CLOB,
    initiated_by VARCHAR2(100) NOT NULL,
    reviewed_by VARCHAR2(100),
    initiated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    reviewed_at TIMESTAMP(6) WITH TIME ZONE,

    -- CIF synchronization
    cif_sync_status VARCHAR2(20) NOT NULL,
    sync_retry_count NUMBER(2) DEFAULT 0 NOT NULL,
    last_sync_attempt_at TIMESTAMP(6) WITH TIME ZONE,
    last_sync_error CLOB,
    cif_synced_at TIMESTAMP(6) WITH TIME ZONE,

    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    version NUMBER DEFAULT 0 NOT NULL,

    CONSTRAINT chk_kyc_status
        CHECK (
            kyc_status IN (
                           'PENDING',
                           'FLAGGED',
                           'APPROVED',
                           'REJECTED'
                )
            ),

    CONSTRAINT chk_kyc_decision
        CHECK (
            decision IS NULL
                OR decision IN ('APPROVED', 'REJECTED')
            ),

    CONSTRAINT chk_kyc_sync_status
        CHECK (
            cif_sync_status IN (
                                'PENDING',
                                'SYNCED',
                                'FAILED'
                )
            ),

    CONSTRAINT chk_kyc_retry_count
        CHECK (
            sync_retry_count BETWEEN 0 AND 5
            )
);

CREATE INDEX idx_kyc_cif_id
    ON kyc(cif_id);