--liquibase formatted sql

--changeset devansh:002

CREATE TABLE kyc_document
(
    document_id NUMBER
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    kyc_id NUMBER NOT NULL,

    document_type VARCHAR2(30) NOT NULL,

    original_file_name VARCHAR2(500) NOT NULL,

    content_type VARCHAR2(100) NOT NULL,

    file_size_bytes NUMBER(12) NOT NULL,

    document_content BLOB NOT NULL,

    verification_status VARCHAR2(20) NOT NULL,

    verification_remarks CLOB,

    verified_by VARCHAR2(100),

    verified_at TIMESTAMP(6) WITH TIME ZONE,

    uploaded_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    version NUMBER DEFAULT 0 NOT NULL,

    CONSTRAINT fk_kyc_document_kyc
        FOREIGN KEY (kyc_id)
            REFERENCES kyc(kyc_id),

    CONSTRAINT uq_kyc_document_type
        UNIQUE (kyc_id, document_type),

    CONSTRAINT chk_document_type
        CHECK (
            document_type IN (
                              'PAN',
                              'AADHAAR',
                              'ADDRESS_PROOF',
                              'SALARY_PROOF'
                )
            ),

    CONSTRAINT chk_document_content_type
        CHECK (
            content_type IN (
                             'image/png',
                             'image/jpeg',
                             'application/pdf'
                )
            ),

    CONSTRAINT chk_document_verification
        CHECK (
            verification_status IN (
                                    'PENDING',
                                    'VERIFIED',
                                    'MISMATCH'
                )
            ),

    CONSTRAINT chk_document_file_size
        CHECK (
            file_size_bytes > 0
            )
);

CREATE INDEX idx_kyc_document_kyc_id
    ON kyc_document(kyc_id);